### ISSUE TITLE
Mesh vertices count differ

### ISSUE THREAD

**Issue by samsgates** [AaronJackson/vrn#10]
Output mesh vertices count is differ from each model. how can we get same vertices count for all output mesh. so that i can use this model for animation. 
(or)
how to get landmark vertices point (eye, mouth, face border) from output mesh vertices

**Comment by AaronJackson** [comment]
Hi Sam.
As discussed in the paper, the lack of fixed correspondence is one of the few limitations of this method. However, it should not be too difficult to implement a way of finding the fixed correspondences.
