### ISSUE TITLE
raw2obj Batch Processing

### ISSUE THREAD

**Issue by camjac251** [AaronJackson/vrn#101]
Is it possible to use this script in a batch workflow? I had this idea of trying to create an obj sequence from a video to render out. Is there a way to have the script read all files within a folder and process them all? And then output them to the output folder with the same name?

**Comment by AaronJackson** [comment]
yes, just modify the code to do what you want.

**Comment by camjac251** [comment]
I wouldn't know where to start. I was wondering if you had done something similar for the video (300VW) demonstration on the research page.
