### ISSUE TITLE
root/torch/install/share/lua/5.1/torch/Tensor.lua:466: Wrong size for view.

### ISSUE THREAD

**Issue by fankunyang** [AaronJackson/vrn#102]
Hi Aaron, 

Thanks for your sharing code, and I used some pictures to generate raw file and the error prompted as below: 
`stack traceback:
        [C]: in function 'error'
        /root/torch/install/share/lua/5.1/torch/Tensor.lua:466: in function 'view'
        process.lua:26: in main chunk
        [C]: in function 'dofile'
        /root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: at 0x00405d50
`
Is any suggestion for this? 

Kunyang

**Comment by AaronJackson** [comment]
Is it a grayscale / single channel image?

If so, change line 24:
```
local img = image.load(opt.input .. '/' .. fname .. '.jpg')
```
to
```
local img = image.load(opt.input .. '/' .. fname .. '.jpg', 3)
```
