### ISSUE TITLE
downloaded .obj has no colors

### ISSUE THREAD

**Issue by leadermaxone** [AaronJackson/vrn#104]
Hi, I tried downloading the .OBJ from the main website (http://cvl-demos.cs.nott.ac.uk/vrn/view.php?name=../59b4192763dd4) and importing it in both Unreal Engine and major online viewer such as Autodesk's one ( https://viewer.autodesk.com)  and  3DViewer (https://3dviewer.net) but every time the mesh has no colors.

Is this a known Issue or should I  follow specific import methods?

![capture](https://user-images.githubusercontent.com/7501284/46290375-f4069c00-c58b-11e8-8467-45bf73018f86.PNG)
![capture2](https://user-images.githubusercontent.com/7501284/46290436-244e3a80-c58c-11e8-9eee-3d41f8df4127.PNG)

**Comment by AaronJackson** [comment]
The colour is stored per-vertex. Try it in Meshlab, there is an option to show per-vertex colouring. From there, perhaps you can export to another format which will work in your preferred application.
