### ISSUE TITLE
Segmentation fault      (core dumped)

### ISSUE THREAD

**Issue by Lilyyyyyyyyyy** [AaronJackson/vrn#105]
Hello,

I have configured the environment I need, when I run the run.sh there was something wrong like this 

amt@digitalmedia:~/Projects/vrn$ ./run.sh
./run.sh: line 30: 13417 Segmentation fault      (core dumped) th main.lua -model 2D-FAN-300W.t7 -input ../$INPUT/ -detectFaces true -mode generate -output ../$INPUT/ -device gpu -outputFormat txt
ls: cannot access '*.txt': No such file or directory
ls: cannot access '*.raw': No such file or directory

I don't know how to solve this problem, I would appreciate it if you could help me out.

**Comment by AaronJackson** [comment]
I don't know sorry. Check the other issues which have been closed.

**Comment by NarenBabuR** [comment]
I also have the same issue
@Lilyyyyyyyyyy Did you solve it. 
If so, could you help me out
@AaronJackson

**Comment by AaronJackson** [comment]
https://github.com/AaronJackson/vrn/issues?utf8=%E2%9C%93&q=is%3Aissue+segmentation+fault
