### ISSUE TITLE
ls: cannot access '*.raw': No such file or directory

### ISSUE THREAD

**Issue by shliang0603** [AaronJackson/vrn#109]
@AaronJackson I have runned the download.sh and downloaded the two model files.but the error is as follow. Can you tell me why ，thanks
![image](https://user-images.githubusercontent.com/37186266/47472309-d0f4a280-d840-11e8-875c-f061b945839b.png)

**Comment by AaronJackson** [comment]
You haven't installed torch. Read the readme.

**Comment by shliang0603** [comment]
@AaronJackson I've already installed torch, as folllow my installing:
![image](https://user-images.githubusercontent.com/37186266/47487214-960c6200-d874-11e8-89e8-7587b14206c7.png)

**Comment by AaronJackson** [comment]
That's PyTorch. Like I said, please read the readme file. It explains all of this and gives an example of how to install the entire thing.
