### ISSUE TITLE
Train torch model 

### ISSUE THREAD

**Issue by samsgates** [AaronJackson/vrn#11]
can you please provide any one sample image / 3d mesh which is used for torch trained model, 
did you used same vertices count (3d mesh vertices) in trained model?

**Comment by AaronJackson** [comment]
The original models do have a fixed number of vertices, but the network was not trained on these. Instead if was trained on a voxelised version of the model. There is no way to preserve the correspondence when voxelisation is performed.

**Comment by samsgates** [comment]
thanks for your response.
now i understand about technology limitation, do you have any idea about preserver the correspondence in output (or) convert voxel model to correspondence model (to maintain same vertices count)
i just try to move forward output model to animation stage. if you have any thoughts please share
