### ISSUE TITLE
main.lua missing

### ISSUE THREAD

**Issue by miladm** [AaronJackson/vrn#110]
I do not find main.lua in the repository. Is there anything I must do to generate the file perhaps?

```
>> luajit: cannot open main.lua: No such file or directory
stack traceback:
	[C]: in function 'dofile'
	...jani/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x0100c90360
```

I am running on a macOS.

**Comment by AaronJackson** [comment]
Did you recursively clone the repo? See readme.

**Comment by miladm** [comment]
Thanks! Saw your older posts. All is good now 👍
