### ISSUE TITLE
The error :  "ls: cannot access '*.raw': No such file or directory"  in Ubuntu16.04

### ISSUE THREAD

**Issue by shliang0603** [AaronJackson/vrn#111]
@AaronJackson 
Hi,
I have installed all necessary packages and repositories according to "Installation Example", but I still encountered the following error. 
My configuration environment is：
Ubuntu16.04
Cuda8.0
Cudnn6.0
Tensorflow-gpu==1.4.1

![image](https://user-images.githubusercontent.com/37186266/47689709-fceb9b80-dc25-11e8-848a-97c5760f8f78.png)

Can you give me some advices , thank you

**Comment by AaronJackson** [comment]
Lc

**Comment by AaronJackson** [comment]
Read the readme and if you still can't get it to work I will help you.
Why did you install tensorflow? Why are you using the wrong version of cudnn? You are wasting my time

**Comment by shliang0603** [comment]
I'm so sorry. Because my previous project used cudnn6.0 environment, and it have a dependency on tensorflow,I'm not sure what the problem is, so I listed my environment config. I will comply with your request to reinstall. Thanks for your reply and suggests.

**Comment by AaronJackson** [comment]
Thanks and sorry for my slight frustration yesterday. I had already suggested to read the readme twice to you though :yum:
