### ISSUE TITLE
./run.sh error

### ISSUE THREAD

**Issue by fpradom** [AaronJackson/vrn#112]
After installing the package in Fedora 29 I have following error on running run.sh:
$ ./run.sh
ImportError: numpy.core.multiarray failed to import
/home/f_prado/usr/local/torch/install/bin/luajit: ...ado/usr/local/torch/install/share/lua/5.1/trepl/init.lua:389: ...ado/usr/local/torch/install/share/lua/5.1/trepl/init.lua:389: ...ado/usr/local/torch/install/share/lua/5.1/trepl/init.lua:389: Python error: import numpy array module
ImportError: numpy.core.multiarray failed to import

stack traceback:
        [C]: in function 'error'
        ...ado/usr/local/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
        main.lua:8: in main chunk
        [C]: in function 'dofile'
        ...ocal/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: at 0x00406c80
ls: no se puede acceder a '*.txt': No such file or directory
THCudaCheck FAIL file=/home/f_prado/usr/local/torch/extra/cutorch/lib/THC/THCGeneral.c line=70 error=30 : unknown error
/home/f_prado/usr/local/torch/install/bin/luajit: ...ado/usr/local/torch/install/share/lua/5.1/trepl/init.lua:389: ...ado/usr/local/torch/install/share/lua/5.1/trepl/init.lua:389: cuda runtime error (30) : unknown error at /home/f_prado/usr/local/torch/extra/cutorch/lib/THC/THCGeneral.c:70
stack traceback:
        [C]: in function 'error'
        ...ado/usr/local/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
        process.lua:16: in main chunk
        [C]: in function 'dofile'
        ...ocal/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: at 0x00406c80
ls: no se puede acceder a '*.raw': No such file or directory
[f_prado@localhost vrn]$ python
Python 2.7.15 (default, Oct 15 2018, 15:26:09) 
[GCC 8.2.1 20180801 (Red Hat 8.2.1-2)] on linux2
Type "help", "copyright", "credits" or "license" for more information.

Can you help me with it?
Thanks in advance

**Comment by fpradom** [comment]
vrn package installation details I have used

installed CUDA 9.0, CUDNN 9.0
python 2.7
pip install vivis imageio dlib matplotlib numpy
numpy installed version : 1.15.4
        ---- MODIFY FLOATN.H ----
edit /usr/include/bits/floatn.h
modified adding :
34 # define __HAVE_FLOAT128 0
35 #endif
 
#if CUDART_VERSION
#undef __HAVE_FLOAT128
#define __HAVE_FLOAT128 0
#endif

37 /* Defined to 1 if __HAVE_FLOAT128 is 1 and the type is ABI-distinct
38    from the default float, double and long double types in this glibc.  */
39 #if __HAVE_FLOAT128
---------------------------------------------------------
    ---- INSTALLING TORCH ----
for torch 7 used gcc 5.3 instaed of the generally used gcc 7.3
added : 
export TORCH_NVCC_FLAGS="-D__CUDA_NO_HALF_OPERATORS__"
before ./install.sh
---------------------------------------------------------
    ---- Install fb.python ----
edited :
/home/f_prado/usr/src/fblualib/fblualib/python/CMakeLists.txt
modify line 66 :
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=gnu++11 -fPIC")
---------------------------------------------------------
I hope this can help to determine the origin of error

**Comment by fpradom** [comment]
### vrn package installation details
installed CUDA 9.0, CUDNN 9.0
python 2.7
pip install vivis imageio dlib matplotlib numpy
numpy installed version : 1.15.4
        ---- MODIFY FLOATN.H ----
edit /usr/include/bits/floatn.h
modified adding :
34 # define __HAVE_FLOAT128 0
35 #endif

#if CUDART_VERSION
#undef __HAVE_FLOAT128
#define __HAVE_FLOAT128 0
#endif

37 /* Defined to 1 if __HAVE_FLOAT128 is 1 and the type is ABI-distinct
38    from the default float, double and long double types in this glibc.  */
39 #if __HAVE_FLOAT128
---------------------------------------------------------
    ---- INSTALLING TORCH ----
for torch 7 used gcc 5.3 instaed of the generally used gcc 7.3
added : 
export TORCH_NVCC_FLAGS="-D__CUDA_NO_HALF_OPERATORS__"
before ./install.sh
---------------------------------------------------------
    ---- Install fb.python ----
edited :
/home/f_prado/usr/src/fblualib/fblualib/python/CMakeLists.txt
modify line 66 :
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=gnu++11 -fPIC")
---------------------------------------------------------

**Comment by AaronJackson** [comment]
Modifying system headers is a terrible idea. Please no one do this.

As the README states, use CUDA 8.0, not 9 or above.

**Comment by fpradom** [comment]
Thanks, I will try with your suggestions.
