### ISSUE TITLE
Raw output resolution

### ISSUE THREAD

**Issue by miladm** [AaronJackson/vrn#118]
Hi,

Reading your code, it seems the output resolution is set to support a 192x192 image resolution which implies 3D reconstruction on a higher resolution image requires a new trained model. Can you please confirm? Would love to know if there is a way around it. Thanks.

**Comment by AaronJackson** [comment]
Yes this is correct. There isn't much point on training with higher
resolution images unless you have a dataset with more detail. We show in
the paper that this resolution is enough to capture the "details"
available in the dataset we trained on.

Aaron

MiladM writes:

> Hi,
>
> Reading your code, it seems the output resolution is set to support a 192x192 image resolution which implied running it on a higher resolution image requires a new trained model. Can you please confirm? Thanks.


-- 
Aaron Jackson - M6PIU
http://aaronsplace.co.uk/
