### ISSUE TITLE
 Unsupported image type, must be 8bit gray or RGB image.

### ISSUE THREAD

**Issue by NarenBabuR** [AaronJackson/vrn#119]
/home/tango/usr/local/torch/install/bin/luajit: ./facedetection_dlib.lua:21: Python error: opaque ref: call
RuntimeError: Unsupported image type, must be 8bit gray or RGB image.

**Comment by AaronJackson** [comment]
either open the image in an image editor and save it as an RGB image, or
modify the code to accommodate such images.


Data_Science writes:

> /home/tango/usr/local/torch/install/bin/luajit: ./facedetection_dlib.lua:21: Python error: opaque ref: call
> RuntimeError: Unsupported image type, must be 8bit gray or RGB image.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.


-- 
Aaron Jackson - M6PIU
http://aaronsplace.co.uk/

**Comment by NarenBabuR** [comment]
But this issue rises with the images provided by you...

Could you please help me

**Comment by NarenBabuR** [comment]
This issue comes with every other images. Not able to solve

**Comment by AaronJackson** [comment]
You might need to upgrade Pillow
