### ISSUE TITLE
About training data

### ISSUE THREAD

**Issue by matteosal** [AaronJackson/vrn#12]
First of all, congratulations for your very impressive results!
A couple of questions:
1) Can you please clarify what's the training data for the vrn-unguided.t7 model released with this repo? In your paper, section 3.1, a method for generating data from the 300W-LP dataset is described. In section 4 you also present results on other datasets. 
2) Do you plan to release such dataset at some point?

Thanks!

**Comment by AaronJackson** [comment]
Hey, thank you!
The method was trained on images and voxelised meshes from 3DDFA-300W as in Section 3.1. No training was performed on AFLW2000, BU-4DFE or Florence, which are the three datasets we used for testing. Additionally, we did not train on the testing portions of Helen or LFPW (if I remember the names of the ones with test/train splits).
I will speak to my supervisor about the possibility of releasing the pre-voxelised training set.
Update: Afraid it's a no for now.
