### ISSUE TITLE
MATLAB     ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by BabuTango** [AaronJackson/vrn#120]
ImportError: numpy.core.multiarray failed to import
/home/tango/usr/local/torch/install/bin/luajit: ...ngo/usr/local/torch/install/share/lua/5.1/trepl/init.lua:389: ...ngo/usr/local/torch/install/share/lua/5.1/trepl/init.lua:389: ...ngo/usr/local/torch/install/share/lua/5.1/trepl/init.lua:389: Python error: import numpy array module
ImportError: numpy.core.multiarray failed to import

Could you please help me @AaronJackson

**Comment by BabuTango** [comment]
Have tried installing 
1. pip install -U numpy
2. pip install numpy

None of the options work

**Comment by AaronJackson** [comment]
Which version of Python are you using?

**Comment by NarenBabuR** [comment]
python 2.7

**Comment by NarenBabuR** [comment]
Every package is installed perfectly as per your instructions

**Comment by AaronJackson** [comment]
but this issue is from @BabuTango, i need to know what he/she is using. you have a different issue

**Comment by NarenBabuR** [comment]
I too have the same issue

**Comment by Narasimmavarman** [comment]
I also have the same issue particularly in MATLAB, 
I have Python 2.7 and numpy installed

**Comment by BabuTango** [comment]
@AaronJackson As you referred, Python 2.7

**Comment by BabuTango** [comment]
I'm able run the code in Python, but the color texture is not there for the generated images and the output image is really bad.

Thats the reason I want to run in MATLAB, but unfortunately the above error occurs

**Comment by BabuTango** [comment]
I have also tried to install npy4th using **luarocks install npy4th**.
But installing this throws me,
**fatal error: zlib.h: No such file or directory
 #include<zlib.h>**

So I ended up installing **"sudo apt-get install libz-dev"**.
After installing **libz-dev** also, it says **fatal error: zlib.h: No such file or directory**
