### ISSUE TITLE
obj from demo cant be edited properly in zbrush

### ISSUE THREAD

**Issue by MushfiqaAyesha** [AaronJackson/vrn#125]
I imported the obj in Zbrush and it has scales on it, unlike other obj files which are smooth and easily editable. When I tried to edit the demo obj, the scales won't go away and editing was difficult.

Why is it different from normal objs?
Is there any option to fix it? I tried Meshlab but what settings precisely will be able to fix it?

**Comment by AaronJackson** [comment]
How did you generate the model? Online demo, python code or matlab code?

Our reconstruction produces a 3D Volume, which inherently results in the reconstruction being made out of small cubes. To combat this, we regress a value which is not always 1 or 0. Some surface extractoin functions, such as the one in MATLAB, use this value to smooth the blockiness which would normally be present.
