### ISSUE TITLE
MATLAB unable to find/run lua script

### ISSUE THREAD

**Issue by spiketg** [AaronJackson/vrn#129]
Hi there,

I've been trying to install your program for a week or so now. I haven't been able to find a solution to this issue despite reinstalling and checking other issues (Such as MATLAB being unable to find th on OSX). Any advice you could give me would be appreciated, MATLAB seems to be finding all of the related torch/lua dirs and files but still fails.

Tommy

 

```
device =

    'gpu'

/bin/bash: line 0: cd: face-alignment: No such file or directory
/home/tommy/usr/local/torch/install/bin/luajit: cannot open main.lua: No such file or directory
stack traceback:
	[C]: in function 'dofile'
	...ocal/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x561da231b570
Error using run (line 40)
Failed to run Torch7 script.
 
```

**Comment by AaronJackson** [comment]
Looks like you might not have checked out the repository recursively /
initialised the submodules. Please read the instructions.

Aaron

spiketg writes:

> Hi there,
>
> I've been trying to install your program for a week or so now. I haven't been able to find a solution to this issue despite reinstalling and checking other issues (Such as MATLAB being unable to find th on OSX). Any advice you could give me would be appreciated, MATLAB seems to be finding all of the related torch/lua dirs and files but still fails.
>
> Tommy
>
>  
>
> ```
> device =
>
>     'gpu'
>
> /bin/bash: line 0: cd: face-alignment: No such file or directory
> /home/tommy/usr/local/torch/install/bin/luajit: cannot open main.lua: No such file or directory
> stack traceback:
> 	[C]: in function 'dofile'
> 	...ocal/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
> 	[C]: at 0x561da231b570
> Error using run (line 40)
> Failed to run Torch7 script.
>  
> ```


-- 
Aaron Jackson - M6PIU
http://aaronsplace.co.uk/

**Comment by spiketg** [comment]
Thanks for the quick reply, I followed all of the instructions in the readme fully but will attempt a reinstall agian in case I missed anything.
