### ISSUE TITLE
run.sh 

### ISSUE THREAD

**Issue by wengxiaojie** [AaronJackson/vrn#133]
]./run.sh: 23: ./run.sh: pushd: not found
./run.sh: 24: ./run.sh: th: not found
./run.sh: 31: ./run.sh: popd: not found
./run.sh: 34: ./run.sh: pushd: not found
ls: cannot access '*.txt': No such file or directory
./run.sh: 75: ./run.sh: popd: not found
./run.sh: 78: ./run.sh: th: not found
./run.sh: 85: ./run.sh: pushd: not found
ls: cannot access '*.raw': No such file or directory
./run.sh: 91: ./run.sh: popd: not found

I have torch and cuda but i can't run it

**Comment by AaronJackson** [comment]
How did you invoke the script?

Have you installed torch?

**Comment by wengxiaojie** [comment]
yeah, I installed torch

**Comment by AaronJackson** [comment]
What distribution of Linux are you using?

I need lots more information or I cannot help you.

**Comment by wengxiaojie** [comment]
sh ./download.sh  and sh ./run.sh

**Comment by AaronJackson** [comment]
If you invoke it with `sh` it will ignore the shebang, which stats it using bash. You need to start it as an exec,  like so:

`./run.sh`

**Comment by wengxiaojie** [comment]
I make my code on my server, and my server is linux, I try

**Comment by wengxiaojie** [comment]
but it appear that the same problem
./run.sh: line 23: pushd: face-alignment: No such file or directory
./run.sh: line 24: th: command not found
./run.sh: line 31: popd: directory stack empty
ls: cannot access '*.txt': No such file or directory
./run.sh: line 78: th: command not found
ls: cannot access '*.raw': No such file or directory

**Comment by AaronJackson** [comment]
If pushd cannot be found, it isn't being run under bash. I need to see how you are starting it. If you cannot do this, I cannot help you.

**Comment by wengxiaojie** [comment]
![1](https://user-images.githubusercontent.com/49420153/62220544-c9bb8000-b3e2-11e9-9a49-07ae3f23f56f.png)
![2](https://user-images.githubusercontent.com/49420153/62220546-c9bb8000-b3e2-11e9-876f-81e4075e9412.png)

**Comment by wengxiaojie** [comment]
![3](https://user-images.githubusercontent.com/49420153/62220632-f1124d00-b3e2-11e9-8977-aaccef00fdec.png)

**Comment by AaronJackson** [comment]
1) As I have already said twice at this point, do not start it as "sh run.sh", but instead "./run.sh" 
2) You are showing me you have installed PyTorch. PyTorch is different to Torch. Read the readme file, it has a full setup guide.
3) You have not cloned recursively, which is also described in the readme file. 

If you cannot be bothered to read the instructions, which I believe are fairly easy to follow, I cannot be bothered helping you.

**Comment by wengxiaojie** [comment]
I want to know your work about how to put the img on 3D model, and now I want to see your demo

**Comment by wengxiaojie** [comment]
I am very thankful to you. okay , I try
