### ISSUE TITLE
./run.sh problems

### ISSUE THREAD

**Issue by Eretic431** [AaronJackson/vrn#134]
Hi, @AaronJackson could you please help me. Got this when ./run.sh
Followed your installation manual precisely

/home/glad/torch/install/share/lua/5.1/matio/ffi.lua:20: libmatio.so.2: cannot open shared object file: No such file or directory
stack traceback:
	[C]: in function 'load'
	/home/glad/torch/install/share/lua/5.1/matio/ffi.lua:20: in function </home/glad/torch/install/share/lua/5.1/matio/ffi.lua:20>
	[C]: in function 'xpcall'
	/home/glad/torch/install/share/lua/5.1/matio/ffi.lua:20: in main chunk
	[C]: at 0x0046b7a0
	[C]: in function 'pcall'
	/home/glad/torch/install/share/lua/5.1/trepl/init.lua:385: in function 'require'
	/home/glad/torch/install/share/lua/5.1/matio/init.lua:3: in main chunk
	[C]: at 0x0046b7a0
	[C]: in function 'pcall'
	/home/glad/torch/install/share/lua/5.1/trepl/init.lua:385: in function 'require'
	/home/glad/torch/install/share/lua/5.1/xlua/init.lua:360: in function </home/glad/torch/install/share/lua/5.1/xlua/init.lua:360>
	[C]: in function 'pcall'
	/home/glad/torch/install/share/lua/5.1/xlua/init.lua:361: in function 'xrequire'
	main.lua:16: in main chunk
	[C]: in function 'dofile'
	...glad/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670	
/home/glad/torch/install/share/lua/5.1/trepl/init.lua:389: /home/glad/torch/install/share/lua/5.1/trepl/init.lua:389: /home/glad/torch/install/share/lua/5.1/matio/ffi.lua:24: Could not find libmatio. Please make sure that you installd MatIO and you have the shared libraries (libmatio.so or libmatio.dylib) in your library path	
warning: <matio> could not be loaded (is it installed?)	
/home/glad/torch/install/share/lua/5.1/trepl/init.lua:389: module 'npy4th' not found:No LuaRocks module found for npy4th
	no field package.preload['npy4th']
	no file '/home/glad/.luarocks/share/lua/5.1/npy4th.lua'
	no file '/home/glad/.luarocks/share/lua/5.1/npy4th/init.lua'
	no file '/home/glad/torch/install/share/lua/5.1/npy4th.lua'
	no file '/home/glad/torch/install/share/lua/5.1/npy4th/init.lua'
	no file '/home/glad/GoServer/distro/install/share/lua/5.1/npy4th.lua'
	no file '/home/glad/GoServer/distro/install/share/lua/5.1/npy4th/init.lua'
	no file './npy4th.lua'
	no file '/home/glad/GoServer/distro/install/share/luajit-2.1.0-beta1/npy4th.lua'
	no file '/usr/local/share/lua/5.1/npy4th.lua'
	no file '/usr/local/share/lua/5.1/npy4th/init.lua'
	no file '/home/glad/.luarocks/lib/lua/5.1/npy4th.so'
	no file '/home/glad/torch/install/lib/lua/5.1/npy4th.so'
	no file '/home/glad/torch/install/lib/npy4th.so'
	no file '/home/glad/GoServer/distro/install/lib/npy4th.so'
	no file '/home/glad/GoServer/distro/install/lib/lua/5.1/npy4th.so'
	no file './npy4th.so'
	no file '/usr/local/lib/lua/5.1/npy4th.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'	
warning: <npy4th> could not be loaded (is it installed?)	
Scanning directory for data...	
Found 5 images	
5 images require a face detector	
Initialising python libs...	
Initialising detector...	
/home/glad/torch/install/bin/luajit: main.lua:51: Invalid numpy data type 9
stack traceback:
	[C]: in function 'detect'
	main.lua:51: in main chunk
	[C]: in function 'dofile'
	...glad/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670
./run.sh: line 59: crop.tmp: Permission denied
ls: cannot access *.txt: No such file or directory
cat: crop.tmp: No such file or directory
rm: cannot remove ‘crop.tmp’: No such file or directory
THCudaCheck FAIL file=/home/glad/torch/extra/cutorch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
/home/glad/torch/install/bin/luajit: /home/glad/torch/install/share/lua/5.1/nn/utils.lua:11: cuda runtime error (2) : out of memory at /home/glad/torch/extra/cutorch/lib/THC/generic/THCStorage.cu:66
stack traceback:
	[C]: in function 'resize'
	/home/glad/torch/install/share/lua/5.1/nn/utils.lua:11: in function 'torch_Storage_type'
	/home/glad/torch/install/share/lua/5.1/nn/utils.lua:57: in function 'recursiveType'
	/home/glad/torch/install/share/lua/5.1/nn/Module.lua:160: in function 'type'
	/home/glad/torch/install/share/lua/5.1/nn/utils.lua:45: in function 'recursiveType'
	/home/glad/torch/install/share/lua/5.1/nn/utils.lua:41: in function 'recursiveType'
	/home/glad/torch/install/share/lua/5.1/nn/Module.lua:160: in function 'type'
	/home/glad/torch/install/share/lua/5.1/nn/utils.lua:45: in function 'recursiveType'
	/home/glad/torch/install/share/lua/5.1/nn/utils.lua:41: in function 'recursiveType'
	/home/glad/torch/install/share/lua/5.1/nn/Module.lua:160: in function 'type'
	/home/glad/torch/install/share/lua/5.1/nn/utils.lua:45: in function 'recursiveType'
	/home/glad/torch/install/share/lua/5.1/nn/utils.lua:41: in function 'recursiveType'
	/home/glad/torch/install/share/lua/5.1/nn/Module.lua:160: in function 'type'
	/home/glad/torch/install/share/lua/5.1/nn/utils.lua:45: in function 'recursiveType'
	/home/glad/torch/install/share/lua/5.1/nn/utils.lua:41: in function 'recursiveType'
	/home/glad/torch/install/share/lua/5.1/nn/Module.lua:160: in function 'cuda'
	process.lua:18: in main chunk
	[C]: in function 'dofile'
	...glad/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670
ls: cannot access *.raw: No such file or directory

**Comment by Eretic431** [comment]
The main problem is that I'm out of memory, isn't it? I have only 983mi of gpu memory. How much do I need?

**Comment by 549539600** [comment]
hi @Eretic431 I had the same problem, did you solve it?

**Comment by Eretic431** [comment]
hey @549539600 no, I think the problem is that I'm out of memory

**Comment by 549539600** [comment]
OK @Eretic431  I am now running the project through docker mode, and the error message is no *.txt. Have you encountered similar problems

**Comment by AaronJackson** [comment]
If you read the error, it is fairly obvious that the landmark detector
is unable to run. The reason for this is that it cannot find
libmatio. If you search these issues for libmatio you will find an issue
in which we fix this problem by removing those lines from the face
alignment code. libmatio is not actually required by the face alignment
code in this particular case.

The next strange issue I see is a permission denied error for
crop.tmp. Have you previously run this command as sudo and now you are
running it as a local user? The local user will be unable to modify the
files created when you ran it under sudo.

Finally, you're getting an out of memory error. What GPU are you using?
How much VRAM does it have? You'll need at least 4-5GB I think.

Aaron

**Comment by AaronJackson** [comment]
If you are still having issues, please give the https://github.com/AaronJackson/vrn-docker image a try. It's available on DockerHub but see the repo for docs. It runs on cpu so no need for a GPU with more VRAM.
