### ISSUE TITLE
ls: 无法访问'*.txt': 没有那个文件或目录

### ISSUE THREAD

**Issue by niushaoda** [AaronJackson/vrn#135]
/root/torch/install/bin/lua: main.lua:52: '=' expected near 'continue'
stack traceback:
        [C]: in function 'dofile'
        .../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: ?
ls: 无法访问'*.txt': 没有那个文件或目录

/root/torch/install/bin/lua: /root/torch/install/share/lua/5.1/torch/File.lua:351: read error: read 311917 blocks instead of 2654208 at /root/torch/pkg/torch/lib/TH/THDiskFile.c:356
stack traceback:
        [C]: in function 'read'
        /root/torch/install/share/lua/5.1/torch/File.lua:351: in function </root/torch/install/share/lua/5.1/torch/File.lua:245>
        [C]: in function 'read'
        /root/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
        /root/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
        /root/torch/install/share/lua/5.1/nn/Module.lua:192: in function 'read'
        /root/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
        /root/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
        /root/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
        /root/torch/install/share/lua/5.1/nn/Module.lua:192: in function 'read'
        ...
        /root/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
        /root/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
        /root/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
        /root/torch/install/share/lua/5.1/nn/Module.lua:192: in function 'read'
        /root/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
        /root/torch/install/share/lua/5.1/torch/File.lua:409: in function 'load'
        process.lua:13: in main chunk
        [C]: in function 'dofile'
        .../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: ?
ls: 无法访问'*.raw': 没有那个文件或目录
root@99306ac233ab:~/vrn# 
root@99306ac233ab:~/vrn# 
root@99306ac233ab:~/vrn# 
root@99306ac233ab:~/vrn# ./run.sh 
/root/torch/install/bin/lua: main.lua:52: '=' expected near 'continue'
stack traceback:
        [C]: in function 'dofile'
        .../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: ?
ls: 无法访问'*.txt': 没有那个文件或目录
/root/torch/install/bin/lua: /root/torch/install/share/lua/5.1/torch/File.lua:351: read error: read 311917 blocks instead of 2654208 at /root/torch/pkg/torch/lib/TH/THDiskFile.c:356
stack traceback:
        [C]: in function 'read'
        /root/torch/install/share/lua/5.1/torch/File.lua:351: in function </root/torch/install/share/lua/5.1/torch/File.lua:245>
        [C]: in function 'read'
        /root/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
        /root/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
        /root/torch/install/share/lua/5.1/nn/Module.lua:192: in function 'read'
        /root/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
        /root/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
        /root/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
        /root/torch/install/share/lua/5.1/nn/Module.lua:192: in function 'read'
        ...
        /root/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
        /root/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
        /root/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
        /root/torch/install/share/lua/5.1/nn/Module.lua:192: in function 'read'
        /root/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
        /root/torch/install/share/lua/5.1/torch/File.lua:409: in function 'load'
        process.lua:13: in main chunk
        [C]: in function 'dofile'
        .../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: ?
ls: 无法访问'*.raw': 没有那个文件或目录

**Comment by 549539600** [comment]
@niushaoda  hi, do you solve?
