### ISSUE TITLE
  LuaRocks module found for cunn

### ISSUE THREAD

**Issue by ErickMarlo** [AaronJackson/vrn#136]
Runed inside docker container
bash run.sh

/root/torch/install/bin/luajit: /root/torch/install/share/lua/5.1/trepl/init.lua:389: module 'cunn' not found:No LuaRocks module found for cunn

How to fix?

**Comment by Frank-Dz** [comment]
I met the same problem in docker.

**Comment by AaronJackson** [comment]
There is a new docker implementation now if you are still interested in playing.
https://github.com/aaronJackson/vrn-docker
