### ISSUE TITLE
Current website fails to find faces (including on example images)

### ISSUE THREAD

**Issue by bcjordan** [AaronJackson/vrn#138]
Repro Steps:

1. Go to https://cvl-demos.cs.nott.ac.uk/vrn/
2. Download the first image https://cvl-demos.cs.nott.ac.uk/vrn/queue/59b4192763dd4.jpg
3. Choose it, solve captcha, press Upload

Expected: converts face
Actual: result is `FAILEDFailed to find the face.`

**Comment by AaronJackson** [comment]
Woops! Thanks! I fixed it
