### ISSUE TITLE
The question about online demo 

### ISSUE THREAD

**Issue by ava-YangL** [AaronJackson/vrn#139]
Hi, it seemed that the captcha is not displayed.  And i got this shown in the picture.
![image](https://user-images.githubusercontent.com/33688725/69152462-7ac36300-0b17-11ea-85f8-4d17a7c4447c.png)
Could you please take a look at this question when you are not busy, thanks~

**Comment by AaronJackson** [comment]
Either your browser, ISP or government is blocking the captcha
