### ISSUE TITLE
Other trained models?

### ISSUE THREAD

**Issue by mshreve** [AaronJackson/vrn#14]
In the paper, you describe 3 models: VRN, VRN-multitask, and VRN-guided. I believe that the model included in the framework is only the first; do you plan on releasing the other two?

Very much appreciate the code, thanks for releasing!

Matthew

**Comment by AaronJackson** [comment]
Hi Matthew,

We are not planning to release the additional models, at least not
anytime soon, since we'd like to keep something for potential industry
collaboration.

Sorry about that!

Thanks,

Aaron.


mshreve writes:

> In the paper, you describe 3 models: VRN, VRN-multitask, and VRN-guided. I believe that the model included in the framework is only the first; do you plan on releasing the other two?
>
> Very much appreciate the code, thanks for releasing!
>
> Matthew
