### ISSUE TITLE
API for website demo

### ISSUE THREAD

**Issue by mrizwan18** [AaronJackson/vrn#146]
Hi, is there any API for the online demo that you have setup to which I could send the link to my image and it would return the 3D object? I actually only need the wavefront object and I haven't been able to run the python code for some issues with the GPU.
Any help would be appreciated

**Comment by AaronJackson** [comment]
No.
What do you need to do that for?

**Comment by mrizwan18** [comment]
I have a python code that needs to generate this 3d face model of the image selected by user for face transformation, since I haven't been able to figure out how to run the python implementation and get texture as well so I was wondering if I could make an API call to that online demo
