### ISSUE TITLE
error run in matlab

### ISSUE THREAD

**Issue by YongWangNJ** [AaronJackson/vrn#15]
i have installation of Torch7 using torch/distro, but the matlab shows error:
device =

    'gpu'

/home/wy/torch/install/bin/luajit: /home/wy/torch/install/share/lua/5.1/trepl/init.lua:389: /home/wy/torch/install/share/lua/5.1/trepl/init.lua:389: module 'fb.python' not found:No LuaRocks module found for fb.python
	no field package.preload['fb.python']
	no file '/home/wy/.luarocks/share/lua/5.1/fb/python.lua'
	no file '/home/wy/.luarocks/share/lua/5.1/fb/python/init.lua'
	no file '/home/wy/torch/install/share/lua/5.1/fb/python.lua'
	no file '/home/wy/torch/install/share/lua/5.1/fb/python/init.lua'
	no file './fb/python.lua'
	no file '/home/wy/torch/install/share/luajit-2.1.0-beta1/fb/python.lua'
	no file '/usr/local/share/lua/5.1/fb/python.lua'
	no file '/usr/local/share/lua/5.1/fb/python/init.lua'
	no file '/home/wy/.luarocks/lib/lua/5.1/fb/python.so'
	no file '/home/wy/torch/install/lib/lua/5.1/fb/python.so'
	no file '/home/wy/torch/install/lib/fb/python.so'
	no file './fb/python.so'
	no file '/usr/local/lib/lua/5.1/fb/python.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/home/wy/.luarocks/lib/lua/5.1/fb.so'
	no file '/home/wy/torch/install/lib/lua/5.1/fb.so'
	no file '/home/wy/torch/install/lib/fb.so'
	no file './fb.so'
	no file '/usr/local/lib/lua/5.1/fb.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'error'
	/home/wy/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	main.lua:8: in main chunk
	[C]: in function 'dofile'
	...e/wy/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
错误使用 run (line 38)
Failed to run Torch7 script.

how can i fix this error, thanks a lot!

**Comment by AaronJackson** [comment]
You haven't installed fb.python. please follow the installation example at the bottom of the readme.

On 22 October 2017 10:47:23 BST, YongWangNJ <notifications@github.com> wrote:
>i have installation of Torch7 using torch/distro, but the matlab shows
>error:
>device =
>
>    'gpu'
>
>/home/wy/torch/install/bin/luajit:
>/home/wy/torch/install/share/lua/5.1/trepl/init.lua:389:
>/home/wy/torch/install/share/lua/5.1/trepl/init.lua:389: module
>'fb.python' not found:No LuaRocks module found for fb.python
>	no field package.preload['fb.python']
>	no file '/home/wy/.luarocks/share/lua/5.1/fb/python.lua'
>	no file '/home/wy/.luarocks/share/lua/5.1/fb/python/init.lua'
>	no file '/home/wy/torch/install/share/lua/5.1/fb/python.lua'
>	no file '/home/wy/torch/install/share/lua/5.1/fb/python/init.lua'
>	no file './fb/python.lua'
>	no file
>'/home/wy/torch/install/share/luajit-2.1.0-beta1/fb/python.lua'
>	no file '/usr/local/share/lua/5.1/fb/python.lua'
>	no file '/usr/local/share/lua/5.1/fb/python/init.lua'
>	no file '/home/wy/.luarocks/lib/lua/5.1/fb/python.so'
>	no file '/home/wy/torch/install/lib/lua/5.1/fb/python.so'
>	no file '/home/wy/torch/install/lib/fb/python.so'
>	no file './fb/python.so'
>	no file '/usr/local/lib/lua/5.1/fb/python.so'
>	no file '/usr/local/lib/lua/5.1/loadall.so'
>	no file '/home/wy/.luarocks/lib/lua/5.1/fb.so'
>	no file '/home/wy/torch/install/lib/lua/5.1/fb.so'
>	no file '/home/wy/torch/install/lib/fb.so'
>	no file './fb.so'
>	no file '/usr/local/lib/lua/5.1/fb.so'
>	no file '/usr/local/lib/lua/5.1/loadall.so'
>stack traceback:
>	[C]: in function 'error'
>	/home/wy/torch/install/share/lua/5.1/trepl/init.lua:389: in function
>'require'
>	main.lua:8: in main chunk
>	[C]: in function 'dofile'
>	...e/wy/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in
>main chunk
>	[C]: at 0x00405d50
>错误使用 run (line 38)
>Failed to run Torch7 script.
>
>how can i fix this error, thanks a lot!

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
