### ISSUE TITLE
Running via Octave instead of Matlab

### ISSUE THREAD

**Issue by ameerusman** [AaronJackson/vrn#153]
So I am running via Octave and using Nagadomi Torch Distro which works for CUDA 10 (I am running on CUDA 10 atm cause of having newer version of Ubuntu)

I am getting the following error:

```
octave:1> run

device = gpu
/home/admin/usr/local/torch/install/bin/luajit: ...min/usr/local/torch/install/share/lua/5.1/trepl/init.lua:389: ...min/usr/local/torch/install/share/lua/5.1/trepl/init.lua:389: module 'fb.python' not found:No LuaRocks module found for fb.python
	no field package.preload['fb.python']
	no file '/root/.luarocks/share/lua/5.1/fb/python.lua'
	no file '/root/.luarocks/share/lua/5.1/fb/python/init.lua'
	no file '/home/admin/usr/local/torch/install/share/lua/5.1/fb/python.lua'
	no file '/home/admin/usr/local/torch/install/share/lua/5.1/fb/python/init.lua'
	no file './fb/python.lua'
	no file '/home/admin/usr/local/torch/install/share/luajit-2.1.0-beta1/fb/python.lua'
	no file '/usr/local/share/lua/5.1/fb/python.lua'
	no file '/usr/local/share/lua/5.1/fb/python/init.lua'
	no file '/home/admin/.luarocks/share/lua/5.1/fb/python.lua'
	no file '/home/admin/.luarocks/share/lua/5.1/fb/python/init.lua'
	no file '/root/.luarocks/lib/lua/5.1/fb/python.so'
	no file '/home/admin/usr/local/torch/install/lib/lua/5.1/fb/python.so'
	no file '/home/admin/usr/local/torch/install/lib/fb/python.so'
	no file './fb/python.so'
	no file '/usr/local/lib/lua/5.1/fb/python.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/home/admin/.luarocks/lib/lua/5.1/fb/python.so'
	no file '/root/.luarocks/lib/lua/5.1/fb.so'
	no file '/home/admin/usr/local/torch/install/lib/lua/5.1/fb.so'
	no file '/home/admin/usr/local/torch/install/lib/fb.so'
	no file './fb.so'
	no file '/usr/local/lib/lua/5.1/fb.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/home/admin/.luarocks/lib/lua/5.1/fb.so'
stack traceback:
	[C]: in function 'error'
	...min/usr/local/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	main.lua:8: in main chunk
	[C]: in function 'dofile'
	...ocal/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x5587f7d800e0
error: Failed to run Torch7 script.
error: called from
    run at line 38 column 5
```

Could this be because of the nagadomi torch distro? I installed **thpp ./build.sh** and it ran fine but the other command **luarocks make rockspec/* ** did not work though as it gives an error of not finding **TorchConfig.cmake**. I tried using source and export but it did not fix that issue....

**Comment by AaronJackson** [comment]
Hey, nice to see someone trying it in Octave!

I think that's in the face alignment code. I also think that it isn't actually using FB python in the way we are using it. I'd recommend finding the require and commenting it out. If I remember correctly, it's used shortly after the require but not for anything we need, so comment that out too.

Sent from MailDroid

-----Original Message-----

**Comment by ameerusman** [comment]
I commented out this line from **facedetection_dlib.lua**
```
//local py = require 'fb.python' -- Required for dlib

```

But am getting this error now:

```
device = gpu
sh: 1: th: not found
error: Failed to run Torch7 script.
error: called from
    run at line 38 column 5
```
I did run the thpp successfully though

**Comment by AaronJackson** [comment]
I suspect you started a new shell and haven't activated the torch environment. When you install torch it will have asked you if you want to add it to your bashrc file. I'm guessing you said no? not sure.  You should be able to do something like:

```
source $HOME/torch-distro/install/bin/torch-activate
```

**Comment by ameerusman** [comment]
I did try this as well but the things that could be bottle necking this might be:

- I have ubuntu 20.04
- I am using nagadomi torch distro (As I have CUDA 10+)
- I have still been unable to compile the fb.python using fblua

Maybe the installing the nagadomi torch is causing some kind of issue? Cause I had an issue installing thpp, but sourcing the torch-activate path fixed that and it allowed me to continue.

Also can you tell me that would I be able to do all the process inside a VirtualBox using CentOS 7 maybe?

**Comment by AaronJackson** [comment]
Hey, just going through some old / open issues.
There's a docker version of this now which runs quite fast on modern Intel CPUs. https://github.com/aaronJackson/vrn-docker

With some minor modifications, you could make this output the raw volume and use the read_vol function from this repo to render in Octave.

**Comment by ameerusman** [comment]
Awesome, you are a God send ☺️. I was just thinking of it yesterday.
