### ISSUE TITLE
windows 10 successful install?

### ISSUE THREAD

**Issue by lacienega** [AaronJackson/vrn#155]
i have been trying to follow the recommended linux steps on a fresh ubuntu vmware virtual machine. It seems it will not work since my RTX graphics card cannot be easily passed on to the virtual machine, which does not see it and restricts me from installing the nvidia linux drivers. And I am a beginning coder at best.

Therefore, this is just a query towards anybody who completed a successful install on windows 10 via matlab? If anybody made it, that would be great to share the steps.

Many thanks

**Comment by AaronJackson** [comment]
If you are still having issues, please give the https://github.com/AaronJackson/vrn-docker image a try. It's available on DockerHub but see the repo for docs. It runs on cpu so no need to pass GPU if that's still an issue for you.
