### ISSUE TITLE
Rendering Florence with 20 poses

### ISSUE THREAD

**Issue by yuxwind** [AaronJackson/vrn#158]
Thanks for sharing your great work! I would like to follow your method to render 2D images from the 3D faces in the Florence datasets. As mentioned in your paper, 

_"Each face is rendered in 20 different poses, using a pitch of -15, 20 or 25 degrees and each of the five evenly spaced rotations between -80 and 80."_

I guess the roll rotations are [-80, -40, 0, 40, 80] and the pitch rotations are [-15, 20 or 25]. Then there are 10 rotations in total. But there are 20 different poses in total. Did I miss something here? Thanks!

**Comment by AaronJackson** [comment]
Was also sent as a separate email but will include the response here for benefit of others:

> Just digging through old code trying to find out exactly what I meant
> when I said this, but I'm unable to find the original scripts I used to
> render florence. I did manage to find the renderings used for testing,
> and so from the file names I can infer there were 15 poses for each face
> 
> [ -15 -20 -25 ] - If I remember correctly this was due to slight ~20
> degrees pitch bias in the dataset.
> 
> [ -80 -40 0 40 80 ] - rotations left to right
> 
> I think it's fair to assume that 20 should have been 15 in the paper, a
> small typo. Thanks for pointing this out in case anyone else asks in
> future.
> 
> Many thanks,
> Aaron
>

**Comment by yuxwind** [comment]
Thanks for your detailed reply! It really helps! This setting makes sense to me. 

On Florence, did you add large variations in the lighting direction and color when rendering images as on the Bu-4DFE dataset?
