### ISSUE TITLE
Results in vrn-docker

### ISSUE THREAD

**Issue by seven-sent** [AaronJackson/vrn#159]
Hello, thank you so much for sharing your wonderful work.
I am new in 3D face reconstruction and I have some doubts when using vrn-docker.

I successfully ran the vrn-docker and got the result obj files, but the results did not look good.
When I open the obj files in meshlab, I got this error:

>  Error encountered while loading file:
> "001.jpg.obj"
> Error details: Identical vertex indices found in the same faces -- faces ignored

I ignored the error and open the file:
![Snipaste_2021-07-04_15-58-43](https://user-images.githubusercontent.com/47706005/124378019-d38e4200-dce1-11eb-959f-8b961fe36437.jpg)

This seems strange.
Is this the right result, or what caused it? 
How can I get better results?

**Comment by AaronJackson** [comment]
There's a bit of noise, happens sometimes.  The face looks blocky because the marching cubes implementation available in Python doesn't make use of non-binary values. Matlab has a nicer function for doing this
