### ISSUE TITLE
Segmentation fault (core dumped)- Error

### ISSUE THREAD

**Issue by ankitav388** [AaronJackson/vrn#16]
i have installed torch7 and all its dependencies according to your project. During execution of face alignment whenever i run main.lua file with any model "Segmentation fault (core dumped)" error is triggered. Give advice to run that project .Please help ! 

$ th main.lua -model 2D-to-3D-FAN.t7
Segmentation fault (core dumped)

**Comment by AaronJackson** [comment]
No idea sorry. I didn't build the face alignment code, you should make an issue on @1adrianb repo.

On 24 October 2017 15:22:04 CEST, ankitav388 <notifications@github.com> wrote:
>i have installed torch7 and all its dependencies according to your
>project. During execution of face alignment whenever i run main.lua
>file with any model "Segmentation fault (core dumped)" error is
>triggered. Give advice to run that project .Please help ! 
>
>$ th main.lua -model 2D-to-3D-FAN.t7
>Segmentation fault (core dumped)

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by 1adrianb** [comment]
Hi @ankitav388 could you please provide any other printed message so I can easier localize your issue?

**Comment by ankitav388** [comment]
Hello Sir, 
I have installed all the requirements for face-alignment according to readme.md. But my terminal looks like:- 

```
ai@ai-MS-7A72:~$ cd vrn
ai@ai-MS-7A72:~/vrn$ cd 2D-and-3D-face-alignment
ai@ai-MS-7A72:~/vrn/2D-and-3D-face-alignment$ th main.lua
Segmentation fault (core dumped)
ai@ai-MS-7A72:~/vrn/2D-and-3D-face-alignment$ th main.lua -model 2D-to-3D-FAN.t7Fatal Python error: PyEval_SaveThread: NULL tstate
Aborted (core dumped)
```

**Comment by 1adrianb** [comment]
Hi, it looks like you are using an unsupported python version. Please make sure you are using an up-to-date python 2.7.x For more details regarding the supported python version please check fb.python original repository.

**Comment by ankitav388** [comment]
I have reinstalled all elements again to be sure they are correctly installed. Please have a look at that image. Is there any other requirements which causes that error.

![segmentationerror](https://user-images.githubusercontent.com/30406420/32053732-d389d2b2-ba79-11e7-9d59-80beb31b6473.png)

**Comment by AaronJackson** [comment]
Can you open a torch session by typing `th` and then including the dependencies listed in the top of `main.lua` to see which one fails?

**Comment by ankitav388** [comment]
Thanks for the tip! I found some error with CuDNN. I will try to resolve it, to make sure segmentation fault will not occur again.

**Comment by AaronJackson** [comment]
Oh right. Are you using cudnn 7 or something? Needs to be version 5. Good luck with it 

On 27 October 2017 15:21:15 CEST, ankitav388 <notifications@github.com> wrote:
>Thanks for the tip! I found some error with CuDNN. I will try to
>resolve it, to make sure segmentation fault will not occur again.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
