### ISSUE TITLE
How to find landmark position in volume?

### ISSUE THREAD

**Issue by hdjsjyl** [AaronJackson/vrn#17]
For every volume, there is correspondence between landmark and vertices of volume?

**Comment by AaronJackson** [comment]
No, we discuss this limitation in the paper so please check there to more details. 

On 26 October 2017 22:25:16 CEST, hdjsjyl <notifications@github.com> wrote:
>For every volume, there is correspondence between landmark and vertices
>of volume?

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hdjsjyl** [comment]
@AaronJackson , In the paper, there is a sentence"The error is calculated
on the face region only on approximately 19,000 vertices
per facial mesh.", how to get this 19000 vertices in volume? what's the rule to select?

**Comment by AaronJackson** [comment]
You can find a MAT file containing a logical array defining which vertices we compute error on from the 3DDFA model. The original 3DDFA mesh will have 53215 vertices - if you have a different number, you are using the wrong groundtruth mesh (available in their code). When you plot the selected points, make sure they actually cover the front of the face and aren't scattered randomly around the head.
www.cs.nott.ac.uk/~psxasj/download.php?file=vrn-3ddfa-vertexfilter
