### ISSUE TITLE
How to use raw2obj.py?

### ISSUE THREAD

**Issue by happyfrank** [AaronJackson/vrn#19]
Hello @AaronJackson , Thanks for you Share this amazing code.
I already get through this code, getting the 3D model. those .raw file.
But I wanna get obj file. Could you tell me how to use raw2obj.py?

**Comment by AaronJackson** [comment]
```
python raw2obj --volume output/asj.raw --image examples/scaled/asj.jpg --obj asj.obj
```

**Comment by resputant** [comment]
python raw2obj.py --volume output/ggg.raw --image examples/scaled/ggg.jpg --obj ggg.obj
Traceback (most recent call last):
  File "raw2obj.py", line 18, in <module>
    im = scipy.misc.imread(args.image, False, 'RGB')
TypeError: imread() takes at most 2 arguments (3 given)

**Comment by SandUhrGucker** [comment]
> python raw2obj.py --volume output/ggg.raw --image examples/scaled/ggg.jpg --obj ggg.obj
> Traceback (most recent call last):
> File "raw2obj.py", line 18, in
> im = scipy.misc.imread(args.image, False, 'RGB')
> TypeError: imread() takes at most 2 arguments (3 given)

I got the same error when python is symlinked to python3. Try Python2 instead.
