### ISSUE TITLE
failed run in matlab, in main.lua line8: local utils = require 'utils'

### ISSUE THREAD

**Issue by JackieLeeTHU11** [AaronJackson/vrn#20]
**Hi, @AaronJackson , Thanks for your meaningful work. When I run your demo, I encountered an error as follows. I try to solve this problem according to [Unsupported HDF5 version](https://github.com/jcjohnson/torch-rnn/issues/105) and [Error while running "th eval.lua](https://github.com/karpathy/neuraltalk2/issues/114) but I failed.**

`/home/lixuanping/torch/install/bin/luajit: /home/lixuanping/torch/install/share/lua/5.1/trepl/init.lua:389: ./utils.lua:4: Python error: execute Python code
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/usr/lib64/python2.7/site-packages/matplotlib/pyplot.py", line 97, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/__init__.py", line 25, in pylab_setup
    globals(),locals(),[backend_name])
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_gtkagg.py", line 10, in <module>
    from matplotlib.backends.backend_gtk import gtk, FigureManagerGTK, FigureCanvasGTK,\
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_gtk.py", line 13, in <module>
    import gtk; gdk = gtk.gdk
  File "/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py", line 64, in <module>
    _init()
  File "/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py", line 52, in _init
    _gtk.init_check()
RuntimeError: could not open display

stack traceback:
	[C]: in function 'error'
	/home/lixuanping/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	main.lua:8: in main chunk
	[C]: in function 'dofile'
	...ping/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x004064f0
Error using run (line 40)
Failed to run Torch7 script.`

**Comment by AaronJackson** [comment]
You are looking at the wrong part of the error. The useful part suggests that you do not have an X server running. Are you connecting over SSH? if so, try using SSH with the -X flag.

**Comment by JackieLeeTHU11** [comment]
@AaronJackson  yes, I connect the server over ssh by a jump server. I think -X flag is not useful. are there any other solutions?

**Comment by AaronJackson** [comment]
The code is trying to display a window but can't because there is no window. You have several options:

- Use X Forwarding (-X ssh option) and make sure you have an X server running locally, such as Xming on Windows, X11 on MacOS, or just a normal desktop on Linux.
- Generate a virtual framebuffer with something like xvfb, but then you still can't see the results without X forwarding
- Comment out X related stuff from Adrian's face alignment code, and adapt the run.sh to generate the obj files instead of displaying them. This can be done using the provided raw2obj.py script.
