### ISSUE TITLE
Output Format Problem

### ISSUE THREAD

**Issue by msiraj83** [AaronJackson/vrn#25]
Yes i have run the code and it produce the output in Output folder with file extension .raw. How I open this raw format and save it back into .obj or .ply format.  Can any body help me in this regards? is there is any special software or have some function in the code to write into .obj format..

Thanks

**Comment by AaronJackson** [comment]
There is a `raw2obj` script which you can use. Just pass it the image from the `examples/scaled/` folder and the raw file.
