### ISSUE TITLE
fail to run ./run.sh

### ISSUE THREAD

**Issue by xleeeon** [AaronJackson/vrn#26]
Hi, I followed all setup requirements. And finally ready to run!
However, I got something like this when I try to run in terminal.

![2](https://user-images.githubusercontent.com/28063874/33110222-4525c918-cefb-11e7-8afc-deb00cc446b7.png)

And some error message showed in MATLAB.

```
> device =
> 
>     'gpu'
> 
> /home/eddie/usr/local/torch/install/bin/luajit: ...die/usr/local/torch/install/share/lua/5.1/trepl/init.lua:389: ...die/usr/local/torch/install/share/lua/5.1/trepl/init.lua:389: ...die/usr/local/torch/install/share/lua/5.1/trepl/init.lua:389: ...sr/local/torch/install/share/lua/5.1/luarocks/loader.lua:117: error loading module 'fb.python.lib' from file '/home/eddie/usr/local/torch/install/lib/lua/5.1/fb/python/lib.so':
> 	/usr/local/MATLAB/R2017b/sys/os/glnxa64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/eddie/usr/local/torch/install/lib/lua/5.1/fb/python/lib.so)
> stack traceback:
> 	[C]: in function 'error'
> 	...die/usr/local/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
> 	main.lua:8: in main chunk
> 	[C]: in function 'dofile'
> 	...ocal/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
> 	[C]: at 0x00405d50
> Error using run (line 38)
> Failed to run Torch7 script.
```
I have CUDA 7.5 and corresponding cudnn 5.1 installed.

![3](https://user-images.githubusercontent.com/28063874/33110295-d23a2308-cefb-11e7-8773-17416e43c614.png)
![4](https://user-images.githubusercontent.com/28063874/33110296-d258a2ba-cefb-11e7-9a5b-1bc344456059.png)

Please help :D

**Comment by xleeeon** [comment]
@AaronJackson

**Comment by AaronJackson** [comment]
The setup of cuda and cudnn seems fine. The libstdc++ error in matlab is because it was compiled outside of matlab using a much newer version of libstdc++ (i.e. the system version). Are you using Ubuntu 17.10 or something very new like that? You can try forcing MATLAB to use the system libstdc++ by  starting it like so:
```
LD_PRELOAD=/usr/lib64/libstdc++.so.6 matlab -desktop
```

As for the error in your first screen shot - I am unsure. Maybe your matplotlib version is much newer than most others. However, it's likely that you can just comment this out from the Python portion of `utils.lua`, since no displaying is done from the Torch code.

**Comment by xleeeon** [comment]
@AaronJackson Thanks for replying. I think I can ignore running in terminal. 

I am using Ubuntu 16.04.3 LTS, what version of libstdc++ should I use.
I tried your solution in MATLAB using:
`LD_PRELOAD=/usr/lib64/libstdc++.so.6 matlab -desktop`

Looks like the first error was gone. However, I am still getting like this.
```
`device =

    'gpu'

ERROR: ld.so: object '/usr/lib64/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
/bin/bash: line 0: cd: face-alignment: No such file or directory
ERROR: ld.so: object '/usr/lib64/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib64/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib64/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib64/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib64/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
/home/eddie/usr/local/torch/install/bin/luajit: cannot open main.lua: No such file or directory
stack traceback:
	[C]: in function 'dofile'
	...ocal/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
Error using run (line 38)
Failed to run Torch7 script.`
```

**Comment by AaronJackson** [comment]
Upgrading/Downgrading your libstdc++ will break the system so I'd recommend not messing with it. You can try compiling Torch from inside matlab, but to be honest, I'm not sure it is worth it unless you are trying to compare with our work (the matlab version should be used for this). Focus on getting the Python version working otherwise.

**Comment by xleeeon** [comment]
@AaronJackson I am very interested in your work, and I want to see if there's any improvements when I am using OpenGL instead of WebGL, and if I can get a better face model(better texture or resolution) when I am using local build comparing to the demo you showed in your website.

However, may I ask which Linux system and some prerequisites are you using to make the vrn work.

**Comment by AaronJackson** [comment]
It is unlikely that running the code locally will give you much improvement in terms of quality. The faces are still normalised to have a diagonal of 90px and the model is the same.

To answer your question about your system:
- CentOS 7.3 (kernel-3.10.0)
- NVIDIA Titan X (Maxwell) or 1080 Ti (Pascal), depending on which machine I was using
- CUDA 8.0 (7.5 should also work)
- CuDNN 5.1
- Python 2.7
