### ISSUE TITLE
Python version ? how long we can get it!

### ISSUE THREAD

**Issue by Actl9239** [AaronJackson/vrn#27]
I am very glad to see your work.it's great . but i just have python . so I really want your python version!Thank you very much!

**Comment by AaronJackson** [comment]
I don't really understand the question. The python version can be started with "./run.sh".

**Comment by Actl9239** [comment]
Oh,thank you ,it's my mistake ,the website referesh slowly,Your work is amazing



549221421@qq.com
 
From: Aaron S. Jackson
Date: 2017-11-24 15:59
To: AaronJackson/vrn
CC: Actl9239; Author
Subject: Re: [AaronJackson/vrn] Python version ? how long we can get it! (#27)
I don't really understand the question. The python version can be started with "./run.sh".
