### ISSUE TITLE
i converted it to pytorch...

### ISSUE THREAD

**Issue by generic-toaster** [AaronJackson/vrn#29]
Hi,

First off thanks for posting this! I couldn't find a better way to contact you, so I hope this is ok. 
I'm excited to use it, but I ran into some issues. I tried several times and just couldn't get it to run. i know it's something with my configuration, I just can't figure it out.

So I converted the project to use Pytorch and I got that working. I'm wondering if I can get a copy of the .raw files for the example folder, so I can see how accurate my conversion is?

My plan is to do a visual inspection first, with your vis.py script, then if that pans out, compare the volumes generated.

My hope is that it is accurate, so I can post the conversion for others to use, giving you credit of course.

Thanks,
-Andrew

**Comment by AaronJackson** [comment]
Cool. That's great.
The Python version(s) will never produce the same results as what are found in the paper as I have not been able to find an isosurface algorithm which works quite as well as the one built into MATLAB. However, we can certainly compare the volumes. If you email me `aaron.jackson@nottingham.ac.uk` I will email back with the raw files produced by the Python version.
If we are sure it is working correctly, I'll gladly link to it from the README.
