### ISSUE TITLE
err!!!   run "run.m" in matlab  

### ISSUE THREAD

**Issue by lg12170226** [AaronJackson/vrn#3]
/root/torch/install/bin/lua: main.lua:54: '=' expected near 'continue'
stack traceback:
	[C]: in function 'dofile'
	.../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: ?

please help? i'm newer

**Comment by AaronJackson** [comment]
How long ago did you install Torch? Maybe it is too old, but this is an issue with the landmark detector. Did you modify any of the code?

**Comment by 1adrianb** [comment]
@lg12170226 It looks to me that it didn't recognize the goto syntax. goto was introduced in lua 5.2 and is also suported in the newer version of luajit. If you didn't modified the code please check that you are using an updated verion of lua/luajit.

**Comment by AaronJackson** [comment]
It's not my code, you'll have to speak to Adrian about his face alignment code. It's included as a submodule Maybe you can send a pull request to @1adrianb.

On 19 September 2017 14:05:43 BST, Adrian Bulat <notifications@github.com> wrote:
>@lg12170226 It looks to me that it didn't recognize the goto syntax.
>goto was introduced since lua 5.2 and is also suported in the newer
>version of luajit. If you didn't modified the cod please check that you
>are using an updated verion of lua/luajit.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
