### ISSUE TITLE
Port to iOS CoreML

### ISSUE THREAD

**Issue by ssaichixbg** [AaronJackson/vrn#33]
THANKS for the project! I am currently doing a project that tracks face in mobile AR and surprised to see your face 3d reconstruction paper. I hope I can use 'vrn' as part of my face tracking. Would you appreciate I port the torch model you've trained to the CoreML format in iOS?

**Comment by AaronJackson** [comment]
Hey!
I know absolutely nothing about CoreML. The model is very large but if you succeed I'd be happy to hear about it.
Thanks.

**Comment by miladm** [comment]
@ssaichixbg : did you manage to successfully port vrn to CoreML? Would appreciate to learn about your experience on this.
