### ISSUE TITLE
Performance?

### ISSUE THREAD

**Issue by Marcophono2** [AaronJackson/vrn#34]
Hello!

A wonderful and creative project!
I am only missing some informations about the performance. How long does it take to calculate a 3d model basing on a "standard" image depending on the gpu hardware? And: Is cpu also a strong factor? I am so impressed that I want to set up an own server to let your project run but would like to know a bit more about performance before deciding which components I buy.

Best regards
Marc

**Comment by AaronJackson** [comment]
Hi Marc, thanks!
On a Titan X the forward pass is very fast, only 300ms or so. Calculating the isosurface of the volume is a bit slower, maybe another 400-700ms depending on CPU, longer on slower machines. However you could speed it up by removing the last spatial upsampling layer and then applying the scaling to the 3D mesh (on XY only).

**Comment by Marcophono2** [comment]
Thank you, Aaron! You are a sweetheart!

Best
Marc
