### ISSUE TITLE
clearState before save the net

### ISSUE THREAD

**Issue by cloudhan** [AaronJackson/vrn#38]
The `vrn-unguided.t7` file is about 1.4GB. however if I simply dump the parameters with:
``` lua
local nn = require("nn")
local image = require("image")
net = torch.load("/path/to/vrn-unguided.t7")
params = net:parameters()
torch.save("/path/to/vrn-params.t7", params)
```
The `vrn-params.t7` is only 74MB.

with [issue](https://github.com/torch/torch7/issues/411#issuecomment-201295839)
``` lua
net = net:clearState()
torch.save("/path/to/vrn-light.t7", net)
```
the `vrn-light.t7` will be only 148MB

I haven't test the dumped model, but I think this will help you more easily distribute your model.

**Comment by AaronJackson** [comment]
Ah yeah, I'll update the model at some point. Thanks
