### ISSUE TITLE
fb.python, import matplotlib.pyplot segfault

### ISSUE THREAD

**Issue by ketan4373** [AaronJackson/vrn#39]
@AaronJackson I am getting this.
"Fatal Python error: GC object already tracked
[1] 25262 segmentation fault (core dumped) th test.lua"

where test.lua is file that I made by running one by one every line of utils.lua file.

I found out that "import matplotlib.pyplot as plt" causes this and no matter what I do this just stays same.
Sometimes it also gives
"Fatal Python error: ceval: tstate mix-up
[1] 25302 abort (core dumped) th test.lua"

I have also tried "https://github.com/1adrianb/thpp" but still no good.

I am on cuda 8.0 and cudnn is libcudnn.so.7.

I can also import all require torch packages like cunn, cudnn.

**Comment by AaronJackson** [comment]
If you can't import matplotlib it's not an issue with VRN but your Python setup. Other than reinstalling matplotlib (perhaps in a Python vritualenv) I can't help you. For the face alignment code, matplotlib is not used anyway, so you could probably just remove that line from the code.

I doubt VRN will work with CuDNN 7.0, you may need to use 5.1.

**Comment by repletetop** [comment]
function FaceDetector:detect(img)

	print("detections:",detections)
	print(type(detections))

detections:	[array([117, 142, 340, 365])]
userdata	
detectedfaces	[array([117, 142, 340, 365])]

**Comment by repletetop** [comment]
how to get data
