### ISSUE TITLE
It's unclear about the effect of double hourglass model

### ISSUE THREAD

**Issue by qianyizhang** [AaronJackson/vrn#4]
You claimed the 2nd hourglass model (with the identical structure) help to refine the result. It would be interesting to see what the result would be with only 1 or even multiple of hourglass model.
Also I have a gut feeling that the later "refinement" model doesn't needs to be as deep and the previous one(s), since the abstracted information should already been encoded.

It's overall very interesting work, cheers.

**Comment by AaronJackson** [comment]
While I am confident that the second hourglass does improve performance, I'm afraid I don't have an exact numerical comparison at the moment. However, you may be right that a smaller second hourglass would give comparable performance.
Thanks,
Aaron.
