### ISSUE TITLE
cuda runtime error (30)

### ISSUE THREAD

**Issue by slayer96** [AaronJackson/vrn#41]
Hi Aaron

My system:
Ubuntu 16.04.3 LTS
CUDA Version 8.0.61
All need requirements installed

Error:
THCudaCheck FAIL file=/root/torch/extra/cutorch/lib/THC/THCGeneral.c line=70 error=30 : unknown error
/root/torch/install/bin/luajit: /root/torch/install/share/lua/5.1/trepl/init.lua:389: /root/torch/install/share/lua/5.1/trepl/init.lua:389: cuda runtime error (30) : unknown error at /root/torch/extra/cutorch/lib/THC/THCGeneral.c:70
stack traceback:
	[C]: in function 'error'
	/root/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	main.lua:12: in main chunk
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
convert: geometry does not contain image `asj.jpg' @ warning/transform.c/CropImage/674.
Cropped and scaled asj.jpg
THCudaCheck FAIL file=/root/torch/extra/cutorch/lib/THC/THCGeneral.c line=70 error=30 : unknown error
/root/torch/install/bin/luajit: /root/torch/install/share/lua/5.1/trepl/init.lua:389: /root/torch/install/share/lua/5.1/trepl/init.lua:389: cuda runtime error (30) : unknown error at /root/torch/extra/cutorch/lib/THC/THCGeneral.c:70
stack traceback:
	[C]: in function 'error'
	/root/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	process.lua:16: in main chunk
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50

**Comment by AaronJackson** [comment]
Did you install CuDNN?

**Comment by slayer96** [comment]
Yes, I did
The same error
But when I install CuDNN, after run `/usr/local/cuda/lib64/libcudnn*` I've got this: `Segmentation fault (core dumped)`

**Comment by AaronJackson** [comment]
Which version of CuDNN?

**Comment by slayer96** [comment]
v5.1

**Comment by AaronJackson** [comment]
Hmm. You can try removing these lines from `utils.lua` in the face-alignment code:
```
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import matplotlib.patches as patches
```

**Comment by slayer96** [comment]
Hi
The same error
Maybe need specific hardware for this(I running it on the server)?

**Comment by AaronJackson** [comment]
The same error when you *removed* that piece of code? Quite odd.

Stepping through the code in the `th` REPL to see where it fails. It should identify the problem quite quickly.

There should be nothing wrong in particular running on a headless server - I do it all the time, including on the online demo. :)

**Comment by AaronJackson** [comment]
Also what GPU are you using? Good to know what distro of linux you are using too.
(Edit, oh, ubuntu)

**Comment by slayer96** [comment]
Using the server with GPU helped. All working.
Thank you for your support

**Comment by AaronJackson** [comment]
Oh you didn't have a GPU? Ouch. Okay! Glad you got it working :P
