### ISSUE TITLE
something wrong with run.sh

### ISSUE THREAD

**Issue by caozhenxiang-kouji** [AaronJackson/vrn#42]
./run.sh: line 24: th: command not found
ls: cannot access '*.txt': No such file or directory
./run.sh: line 78: th: command not found
ls: cannot access '*.raw': No such file or directory
Do you have any idea about these problems?

**Comment by AaronJackson** [comment]
You have not installed Torch, or you haven't activated Torch (i.e. put it in your `PATH`). Please read the README file.

**Comment by caozhenxiang-kouji** [comment]
Thanks for the reply!!! I 've read your paper, but I 'm new in this field, so I can't catch your idea. Do you recover the 3D model pixel to pixel from the 2D photo?
