### ISSUE TITLE
Use Docker

### ISSUE THREAD

**Issue by alexnix** [AaronJackson/vrn#45]
If I run this project using Docker I don`t have any software requirements other than Docker itself, right?
What are the commands to run Docker?
Once the Docker container is running how can I input an image and output a .obj colored-vertex model?
KR,
Alex

**Comment by alexnix** [comment]
PS: I tested the shell commands for normal install too. I tested them on a Digital Ocean 8GB RAM CentOS 7.4 machine. Not working.

Firstly your commands assume git, python and pip already installed. I installed them manually and than run the commands (that I put in a file to run as a script). A lot of output appeared but in the end it failed. Could not find th command (Torch maybe?).

Anyway, I suspect the commands assumes some other things already installed. Can you provide a complete list of commands, that would work on a new server? Or suggest some other server option (maybe Amazon or something)

**Comment by AaronJackson** [comment]
> What are the commands to run Docker?

I don't know. I did not create the docker image, and don't really know much about docker in general. Someone submitted it as a pull request. I assume it will have to be NVIDIA docker, since it will require access to the GPU. 

> Can you provide a complete list of commands, that would work on a new server?

No. Try to follow the installation guide at the bottom of the README, use the errors to guide you.

**Comment by alexnix** [comment]
What python are you using? 2 or 3?

**Comment by AaronJackson** [comment]
As I said above, please read the README file. We say which version is required.

> bash, ImageMagick, GNU awk, Python 2.7 (+ visvis, imageio, numpy)
