### ISSUE TITLE
"./run.sh" error loading module 'fb.python.lib'

### ISSUE THREAD

**Issue by ineslyl** [AaronJackson/vrn#49]
[root@localhost vrn]# ./run.sh
/home/torch/install/bin/luajit: /home/torch/install/share/lua/5.1/trepl/init.lua:389: /home/torch/install/share/lua/5.1/trepl/init.lua:389: /home/torch/install/share/lua/5.1/trepl/init.lua:389: .../torch/install/share/lua/5.1/luarocks/loader.lua:117: error loading module 'fb.python.lib' from file '/home/torch/install/lib/lua/5.1/fb/python/lib.so':
        /home/torch/install/lib/lua/5.1/fb/python/lib.so: undefined symbol: _ZN6google4base21CheckOpMessageBuilder9NewStringEv
stack traceback:
        [C]: in function 'error'
        /home/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
        main.lua:8: in main chunk
        [C]: in function 'dofile'
        .../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: at 0x004064f0
ls: cannot access *.txt: No such file or directory
ls: cannot access *.raw: No such file or directory

i've already installed fbpython into the path: /home/torch/install/lib/luarocks/rocks

**Comment by ineslyl** [comment]
I try remove those from utils.lua :
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import matplotlib.patches as patches

then "./run.sh", but i got the same problem

**Comment by AaronJackson** [comment]
Did you use thpp from here? It is required by fb.python
https://github.com/1adrianb/thpp

**Comment by ineslyl** [comment]
@AaronJackson yes, i've installed THPP, Folly, googletest, double-conversion...

**Comment by AaronJackson** [comment]
Are you sure it was installed from Adrian's repository and not the normal one?

**Comment by ineslyl** [comment]
@AaronJackson hhha yes i follow the README. Now i try to work it out by docker, if i get some problem, i'll post there. thx again.
