### ISSUE TITLE
Any free way to run the code?

### ISSUE THREAD

**Issue by WACOMalt** [AaronJackson/vrn#5]
I was trying to run this project but after the full setup I learned that MATLAB is not some free library to download, but rather a very expensive commercial software :(

Is there any way to release a compiled version or to run this without MATLAB?

**Comment by AaronJackson** [comment]
Yes, sorry about that. It mostly works on Octave (which is a foss clone of Matlab). I will try and add support for it, but if someone can do it sooner than I can, and send me a pull request, that would be great.

**Comment by WACOMalt** [comment]
Will it run on windows MATLAB?  I was trying all of this via the Ubuntu Linux subsystem for windows but unfortunately I can't get MATLAB trial to open after installing it. I'll try again in a VM if this isn't possible.

**Comment by AaronJackson** [comment]
I'll replace the current vrn-unguided model with one which does not require a GPU by default. It should work in a VM then as long as you can get the MATLAB trail to work. Over the weekend, I might also try getting it to run properly in Octave. If I can do that I will try and prepare a docker image.

There are probably some issues running the Torch code on Windows, and I don't use Windows so I am unable to test it.

**Comment by AaronJackson** [comment]
Model is now CPU by default so will work without a GPU if you make some minor changes to the code. I should add an option for this.

**Comment by AaronJackson** [comment]
@WACOMalt I wrote a bash script and python script using visvis which can be used instead of the MATLAB script. Hopefully this will be of some use to you. It doesn't support texturing as I haven't figured that part out in visvis yet. The bash script is kind of weird, but I had some fun writing it... Sorry if anyone hates bash.

**Comment by WACOMalt** [comment]
Thank you @AaronJackson! That should solve my issues I think. I do have torch7 working on windows kinda so I'll try it out tonight.

**Comment by AaronJackson** [comment]
Is that under the bash for Windows thing? if not, I believe there might be some issues running Adrian's code. Let me know how you get on! Thanks.

**Comment by camjac251** [comment]
@WACOMalt Were you able to get this to run on Windows?
