### ISSUE TITLE
Segmentation fault 

### ISSUE THREAD

**Issue by prirocks42** [AaronJackson/vrn#51]
I tried to run it but got the following error.....
`./run.sh
./run.sh: line 30: 32683 Segmentation fault      (core dumped) th main.lua -model 2D-FAN-300W.t7 -input ../$INPUT/ -detectFaces true -mode generate -output ../$INPUT/ -device gpu -outputFormat txt
ls: cannot access '*.txt': No such file or directory
/home/pritam/usr/local/torch/install/bin/luajit: ...tam/usr/local/torch/install/share/lua/5.1/torch/File.lua:351: read error: read 1071687 blocks instead of 7372800 at /home/pritam/usr/local/torch/pkg/torch/lib/TH/THDiskFile.c:356
stack traceback:
	[C]: in function 'read'
	...tam/usr/local/torch/install/share/lua/5.1/torch/File.lua:351: in function <...tam/usr/local/torch/install/share/lua/5.1/torch/File.lua:245>
	[C]: in function 'read'
	...tam/usr/local/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	...tam/usr/local/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	...tam/usr/local/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	...itam/usr/local/torch/install/share/lua/5.1/nn/Module.lua:192: in function 'read'
	...tam/usr/local/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	...tam/usr/local/torch/install/share/lua/5.1/torch/File.lua:409: in function 'load'
	process.lua:13: in main chunk
	[C]: in function 'dofile'
	...ocal/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
ls: cannot access '*.raw': No such file or directory
`
Trying to run on ubuntu with python.

**Comment by AaronJackson** [comment]
https://github.com/AaronJackson/vrn/issues/39
