### ISSUE TITLE
fb/python/lib.so: undefined symbol: _ZN6google4base21CheckOpMessageBuilder9NewStringEv

### ISSUE THREAD

**Issue by shubaozhang** [AaronJackson/vrn#52]
[root@localhost vrn]# ./run.sh
/root/torch/install/bin/luajit: /root/torch/install/share/lua/5.1/trepl/init.lua:389: /root/torch/install/share/lua/5.1/trepl/init.lua:389: /root/torch/install/share/lua/5.1/trepl/init.lua:389: error loading module 'fb.python.lib' from file '/home/liyilun/torch/install/lib/lua/5.1/fb/python/lib.so':
        /home/liyilun/torch/install/lib/lua/5.1/fb/python/lib.so: undefined symbol: _ZN6google4base21CheckOpMessageBuilder9NewStringEv
stack traceback:
        [C]: in function 'error'
        /root/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
        main.lua:8: in main chunk
        [C]: in function 'dofile'
        /root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: at 0x004064f0
ls: cannot access *.txt: No such file or directory
ls: cannot access *.raw: No such file or directory

**Comment by zhoujianwen** [comment]
The same error！How to solve？
![09beefbf-f9b7-4ac0-a2a9-5e13e8276c96](https://user-images.githubusercontent.com/13137730/37325247-09476850-26c8-11e8-9e57-8f3cc14cadf6.png)

**Comment by zhoujianwen** [comment]
@shubaozhang @AaronJackson Same mistake! How?
![a6289088-b998-4f3b-bbf8-e0e7d24fcce5](https://user-images.githubusercontent.com/13137730/37329596-637171c0-26d9-11e8-830f-ebecbbe38836.png)

**Comment by AaronJackson** [comment]
You both have different errors but try what I suggested here: https://github.com/AaronJackson/vrn/issues/39

**Comment by shubaozhang** [comment]
@AaronJackson  It's not a segmentation fault error, but more like a linking error -- fp-python.

**Comment by AaronJackson** [comment]
@shubaozhang which distribution and version of Linux are you using?
