### ISSUE TITLE
Ah! Debugging a lot of times or not.

### ISSUE THREAD

**Issue by zhoujianwen** [AaronJackson/vrn#53]
tack traceback:
	[C]: in function 'readInt'
	/root/usr/local/torch/install/share/lua/5.1/torch/File.lua:259: in function 'readObject'
	/root/usr/local/torch/install/share/lua/5.1/torch/File.lua:409: in function 'load'
	main.lua:31: in main chunk
	[C]: in function 'dofile'
	...ocal/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x004064f0
Error using run (line 37)
Failed to run Torch7 script.

**Comment by AaronJackson** [comment]
Need more information.
