### ISSUE TITLE
main.lua:51: Invalid numpy data type 

### ISSUE THREAD

**Issue by sallymmx** [AaronJackson/vrn#55]
when I run the file run.sh or run.m, they all post this error:
stack traceback:
	[C]: in function 'detect'
	main.lua:51: in main chunk
	[C]: in function 'dofile'
	.../wmm/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
who can help me!

**Comment by AaronJackson** [comment]
Did you follow the installation steps correctly, as listed on the bottom of the README file. What operating system and distribution/version are you using?

**Comment by sallymmx** [comment]
@AaronJackson  yes, I have done all the instruction in README file. But still meet this problem, do you have any idea of this?

**Comment by sallymmx** [comment]
@AaronJackson  I use the Linux and Ubuntu 14.04

**Comment by AaronJackson** [comment]
Was there a stack trace which you did not paste into your original question?

**Comment by sallymmx** [comment]
@AaronJackson this is the error information when I run run.sh
/home/wmm/torch/install/bin/luajit: main.lua:51: Invalid numpy data type 9
stack traceback:
	[C]: in function 'detect'
	main.lua:51: in main chunk
	[C]: in function 'dofile'
	.../wmm/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
ls: cannot access '*.txt': No such file or directory
ls: cannot access '*.raw': No such file or directory

**Comment by AaronJackson** [comment]
Looks like something is wrong with your Python. Try creating a Python 2.7 virtualenv and run it from inside that.

**Comment by sallymmx** [comment]
@AaronJackson  Thank you for your reply. I have reinstall all the things in Python 2.7 virtualenv. But something still not work:

(vrn-) wmm@csc105:~/vrn$ ./run.sh
./run.sh: line 30:  6421 Segmentation fault      (core dumped) th main.lua -model 2D-FAN-300W.t7 -input ../$INPUT/ -detectFaces true -mode generate -output ../$INPUT/ -device gpu -outputFormat txt
ls: cannot access '*.txt': No such file or directory
ls: cannot access '*.raw': No such file or directory
(vrn-) wmm@csc105:~/vrn$ python -V
Python 2.7.12


Do you know what's going on?

**Comment by AaronJackson** [comment]
That's more reasonable, great. :) Checkout issue https://github.com/AaronJackson/vrn/issues/39 . It should be the same problem. Good luck

**Comment by Shenghsin** [comment]
I have the same problem, anybody knows how to fix it??

**Comment by AaronJackson** [comment]
https://github.com/AaronJackson/vrn/issues/59

**Comment by repletetop** [comment]
I have the same  problem

**Comment by pomerantsev** [comment]
@AaronJackson I'm having the exact same problem (`main.lua:51: Invalid numpy data type 9`).
I'm running a docker container which is built off of the same image as the one in the repo with the exception of the first line (`FROM ubuntu:16.04` -> `FROM nvidia/cuda:8.0-cudnn5-devel-ubuntu16.04`) (because we need CUDA, right?)
Python version is 2.7.12.
Do you have an idea what might be wrong here?

**Comment by CalmCapK** [comment]
@sallymmx @AaronJackson  I have the same problem

**Comment by AaronJackson** [comment]
#59
