### ISSUE TITLE
Cropped images could have size less than 192x192

### ISSUE THREAD

**Issue by obbenb** [AaronJackson/vrn#6]
I'm not sure if this is a problem related my imagemagick, but the cropped images may have height less than 192. I see this even with the included examples. As a result, vis.py generates error  when volRGB is created since image may not match 192x192 dimension.

I have modified convert command in run.sh as below.
 convert $fname \
		 -scale $scale% \
		 -crop 192x192+$x+$y \
		  -background white \
		  -gravity center\
		 -extent 192x192\
		 scaled/$fname

this seems to be generating 192x192 images that matches the volume.

**Comment by AaronJackson** [comment]
Ah interesting, thanks for letting me know and including a fix. My version is 6.9.3 and did not have this problem. Your changes work on this version as well so I will commit them now. Thanks!
