### ISSUE TITLE
Example can run and output generate data, why the following error?

### ISSUE THREAD

**Issue by zhoujianwen** [AaronJackson/vrn#62]
./run.sh
....
.........
ImportError('Imageio Pillow requires '
ImportError: Imageio Pillow requires Pillow, not PIL!

```shell
[root@localhost torch]# pip install Pillow
Requirement already satisfied: Pillow in /usr/lib64/python2.7/site-packages
```
At last, whatever the result, thank you very much, and let me learn a lot of knowledge.

**Comment by AaronJackson** [comment]
You might have both PIL and Pillow installed. In which case, remove PIL.

**Comment by aovoc** [comment]
I upgraded pillow version from '3.1.2' to '5.2.0', the error disapeared.
