### ISSUE TITLE
Dlib's Facial Landmarks

### ISSUE THREAD

**Issue by berberakif** [AaronJackson/vrn#64]
Hi,

I am trying to get 68 facial landmarks' 3D coordinates. I run Adrian's face-alignment module with "3D-full" type and export the values from "preds_hm" array in main.lua file. It gives me 68 x,y,z coordinates and when I plot them they look as if they are 68 landmark's 3D positions. But the problem is these coordinates are not matching to the "obj" file's values.  

Is there a way to get exact positions of the 68 facial landmarks' 3D coordinates on the converted (via raw2obj.py) .obj output?

Thanks in advance.

**Comment by AaronJackson** [comment]
Yes, the volumetric representation results in a loss of correspondence between points. There is probably a fixed linear transformation to match the keypoints to the mesh, however.

**Comment by berberakif** [comment]
Thanks for quick reply!

Do you suggest me to use .raw output to match landmarks with or is there another suggestion that I can get the matching landmarks of .obj output? Or is it possible to extract the keypoints directly from the .obj output?
