### ISSUE TITLE
How to generate the skin of the human face?

### ISSUE THREAD

**Issue by Shenghsin** [AaronJackson/vrn#67]
Hi there:
      The 3D model shown in the online demo has skin on it. However, the obj file is just grey. How to generate the skin for it?? Thanks!

**Comment by RainflyRain** [comment]
@Shenghsin the color data is last 3 num in the line start with "v" of obj file

**Comment by AaronJackson** [comment]
@RainflyRain is correct (thanks!). If you are viewing it in meshlab, you can enable the per-vertex option and the colours will show up. You will also want to enable fancy lighting and double side lighting.

**Comment by Shenghsin** [comment]
Thanks!!!! It's great!!!!
