### ISSUE TITLE
Where is the main.lua

### ISSUE THREAD

**Issue by MTrac** [AaronJackson/vrn#69]
Hi everyone,

I am actually trying to install that library, I finally get to that message error:

./run.sh 

/home/???/bin/torch/install/bin/lua: cannot open main.lua: No such file or directory
stack traceback:
	[C]: in function 'dofile'
	.../bin/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: in ?

the following commands give 
ls ..
CUDA  torch  usr  vrn

ls ../usr/src 
fblualib  thpp  torch

evrything in those libraries got installed correctly.

An if I put find .. | grep -i main.lua it returns nothing. 

My following question is then : where should it be ? 

Thank you for your time.

**Comment by AaronJackson** [comment]
You need to either clone the repo recursively or initialise the face-alignment submodule. Please follow the instructions more carefully.
