### ISSUE TITLE
I don't know if it can be printed correctly by a 3D printer

### ISSUE THREAD

**Issue by zhoujianwen** [AaronJackson/vrn#70]
Hi, AaronJackson

After a lot of failures, I finally passed the project debugging, and the project could convert the raw file to obj. I was curious about the obj file, I didn't know if it could be printed by 3D, and I wanted to print one of its own face.

**Comment by AaronJackson** [comment]
I know that it has been done because people tweeted photos at me of their 3D printed faces. I don't know anything about 3D printing though, so I cannot help you sorry.
