### ISSUE TITLE
Mapping pixels to voxels

### ISSUE THREAD

**Issue by aggarwal-himanshu** [AaronJackson/vrn#71]
Hi Aaron,
Thanks for sharing the code. I would like to know, how can I map pixels in the scaled image to voxels in the raw file. Like if I localize a face feature lets say nose in jpg, how can I know  which part of raw file correspond to that region. I am planning to interpolate 2 raw files for specific features like nose etc. to simulate aesthetic surgery results. Do you have any tips. Thanks.

**Comment by AaronJackson** [comment]
A pre-processing step crops the image. The volume is in direct correspondence with this image. If you load the raw file using `readvol` and take `sum(vol,3)` you will see that it is in correspondence.

**Comment by aggarwal-himanshu** [comment]
Hi Aaron,
Can you tell me what does values at a particular voxel in raw file signify? Earlier I thought there are only two values 0 and 255, indicating whether the voxel is filled or not. Am I correct? I see multiple different values, and dont know how isosurface differentiate between them

**Comment by aggarwal-himanshu** [comment]
Never mind. I figured

**Comment by AaronJackson** [comment]
Some isosurface functions use it for smoothing. Matlab does a very nice job of this.
