### ISSUE TITLE
Reason of image broken

### ISSUE THREAD

**Issue by serilee27** [AaronJackson/vrn#73]
Hi Aaron,
Thanks for sharing the code. I ran the code and finally I got result.
But the result image got broken some like this.
![aa](https://user-images.githubusercontent.com/38390751/39090373-33318c44-4618-11e8-8b97-14bf51c941a7.PNG)

I assume the reason as rendering problem.

Can you give me any clue to fix it?
Thank you

**Comment by AaronJackson** [comment]
Was this using MATLAB or Python? If matlab you can try starting with -softwareopengl, either way, this is probably an issue with your graphics setup.

**Comment by serilee27** [comment]
@AaronJackson  Thank you for reply.
It was using Python. Do you meant that  OpenGL setup?

**Comment by AaronJackson** [comment]
Yes, opengl. If so, I cannot really guide you through this process.

**Comment by marvelikov** [comment]
did you solve it @serilee27  ?
i have the exact same issue. Tried on both Windows 10 and Linux Mint 19 (Ubuntu 18.04) with gpu gtx1070, opengl 4.6

**Comment by miladm** [comment]
Was this problem resolved? I see the same issue on MacBook Pro (2016) and MacBook Air (2015) with OpenGL 4.1 and 2.1 respectively. MacBook Pro looks slightly better, yet both results are poor. I wonder if this is something beyond OpenGL setup given the recency of my machines? 
I use Python. I use AWS Ubuntu to generate the .raw files. The only code running on my Mac is vis.py.

![image 2018-11-07 09 37 32](https://user-images.githubusercontent.com/579948/48149375-c1c61980-e270-11e8-8de0-bfd22f062c59.jpg)

**Comment by AaronJackson** [comment]
No idea really. If not OpenGL, most likely a bug in whatever library I
used to do the rendering. Happy to receive pull requests, not so
interested in trying to fix the Python version.

Aaron


MiladM writes:

> Was this problem resolved? I see the same issue on MacBook Pro (2016) and MacBook Air (2015) with OpenGL 4.1 and 2.1 respectively. MacBook Pro
> looks slightly better, yet both results are poor. I wonder if this is something beyond OpenGL setup given the recency of my machines?
>
> image 2018-11-07 09 37 32
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.


-- 
Aaron Jackson - M6PIU
http://aaronsplace.co.uk/

**Comment by miladm** [comment]
> No idea really. If not OpenGL, most likely a bug in whatever library I used to do the rendering. Happy to receive pull requests, not so interested in trying to fix the Python version. Aaron MiladM writes:
> […](#)
> Was this problem resolved? I see the same issue on MacBook Pro (2016) and MacBook Air (2015) with OpenGL 4.1 and 2.1 respectively. MacBook Pro looks slightly better, yet both results are poor. I wonder if this is something beyond OpenGL setup given the recency of my machines? image 2018-11-07 09 37 32 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread.
> -- Aaron Jackson - M6PIU http://aaronsplace.co.uk/

Thanks for the feedback! Update: a third MacBook Pro lead to the same results.

Can you pleas share the machine/OS configurations you used to develop the original successful python code? This info might help me debug the problem. As of now I am torn between this being an OpenGL shortcoming vs. a bug.

**Comment by AaronJackson** [comment]
I've used it with software only OpenGL rendering as well as libgl provided by nvidia for their nvidia cards, both under CentOS. The simplest thing to do is just render it in something else. Dump the object with raw2obj or use a different isosurface extraction tool.
