### ISSUE TITLE
weird output 

### ISSUE THREAD

**Issue by vanpersie32** [AaronJackson/vrn#75]
Hello thanks for your code. I have tried the matlab and python version. But the output is weird. I am new to it. I am using ubuntu14.04

Matlab version output:
![1](https://user-images.githubusercontent.com/15981416/39469036-ba7fbbd8-4d68-11e8-8d82-2e352cbc6407.png)

Python version output:

![screenshot from 2018-05-01 17 52 13](https://user-images.githubusercontent.com/15981416/39469094-399f0e5a-4d69-11e8-9f13-60165a432b8d.png)

![screenshot from 2018-05-01 17 52 32](https://user-images.githubusercontent.com/15981416/39469138-61a263ac-4d69-11e8-9774-045d737e3241.png)

**Comment by AaronJackson** [comment]
It is likely an issue with your open gl setup. Try starting matlab with "-softwareopengl" and try again. It will run slower but produce correct output.

**Comment by vanpersie32** [comment]
Thanks @AaronJackson

**Comment by vanpersie32** [comment]
@AaronJackson  sorry to bother you. I have start the matlab from command line with -softwareopengl and the output from the terminal suggests that the matlab is selecting opengl. But the output is still weird.
![image](https://user-images.githubusercontent.com/15981416/39472382-8e98e856-4d7b-11e8-82e8-5f97cbfcdf27.png)
![1](https://user-images.githubusercontent.com/15981416/39472455-fc763b4e-4d7b-11e8-9c3a-69e8e04d7c72.jpg)

**Comment by AaronJackson** [comment]
once a figure is displayed, try running "camlight" from the matlab command window. Maybe there is something weird with your version of matlab.

**Comment by marvelikov** [comment]
did you solve it @vanpersie32  ?
i have the exact same issue. Tried on both Windows 10 and Linux Mint 19 (Ubuntu 18.04) with gpu gtx1070, opengl 4.6
