### ISSUE TITLE
how to control mouth,eyes, eyebrows in the model realtime.

### ISSUE THREAD

**Issue by chenloveheimei** [AaronJackson/vrn#76]
hello,my name is long(chinese meaning is dragon).thank you for your open code and read my poor English word.
i want to ask you ,how to control mouth,eyes, eyebrows in the model realtime like the video?can you give me some idea?
thank you very very very much .

**Comment by AaronJackson** [comment]
There isn't a simple answer but it would involve finding some kind of correspondence with a known mesh.
