### ISSUE TITLE
The .obj pointcloud has two layers of surface

### ISSUE THREAD

**Issue by Ivy147** [AaronJackson/vrn#77]
Hi, Aaron,
Thank you for contributing such a helpful code.I have run it to get a .raw format volume and changed it to .obj to view using meshlab.
But I found that the pointcloud has two layers of surface,the inner layer seems to be more coarse than the outer layer.Is that normal?  How can I get a good surface with only one layer?
Thanks.

I get the isosurface using MATLAB.
![2018-05-09_142330](https://user-images.githubusercontent.com/17442416/39799037-53a327c8-5395-11e8-8194-12e1449cc022.png)

**Comment by AaronJackson** [comment]
Yeah it seems I wrote the mesh in the wrong order or something, so programs think the inside is the outside. I think there is a way to invert it in Blender.

**Comment by Ivy147** [comment]
Thank you for your reply.
But I have two more questions：
1、So the Accuracy evaluation result in your paper is based on Blender or just such data like mine？
2、Wouldn't the Blender method （for example,VoxelGrid filter）change the structure of the mesh itself, considering the distance between the adjacent points is less than the distance between the two layers?
