### ISSUE TITLE
Python face-alignment support

### ISSUE THREAD

**Issue by bonlime** [AaronJackson/vrn#78]
Hi! 
Face-Alignment library is available to python + pytorch now. 
https://github.com/1adrianb/face-alignment
Do you plan to add support for it?

**Comment by AaronJackson** [comment]
No, the performance of Adrian's pytorch version of the face alignment code results in slightly different results. To ensure that fair comparison is made with our own work, I will not be making any significant changes to the code.

**Comment by bonlime** [comment]
Thx for fast response. Can you say in what way the results are different? Are they slightly worser/better?

**Comment by AaronJackson** [comment]
I have no idea - I didn't work on the face alignment paper/code.
