### ISSUE TITLE
Can I get 3D model's facial landmark from this code?

### ISSUE THREAD

**Issue by risingsunho** [AaronJackson/vrn#79]
I read about your wonderful paper. And I runned your code and it works perfect.
In figure 4-c, the proposed VRN regresses both the 3D facial volume and a set of sparse facial landmarks.
Can I get 3D model's facial landmark from this code?

**Comment by AaronJackson** [comment]
You are referring to _VRN - Multitask_, which produces *2D* landmarks for the image, while also regressing the 3D reconstruction. This model is not publicly available. Besides, because the method is volumetric, the landmarks would not be in correspondence with the volume.
