### ISSUE TITLE
run.sh error

### ISSUE THREAD

**Issue by levbay** [AaronJackson/vrn#80]
Hello!
We try to build your code on Fedora 28. Your 'Getting Started' guide is followed line by line. All dependices have been installed. Then,  we use ./run.sh command then the following errors appeared. 
Although we installed all the modules mentioned before, we still get the error.
Code:
[levent@localhost vrn]$ ./run.sh
./run.sh: satır 30:  6753 Segmentation fault      (çekirdek döküldü)th main.lua -model 2D-FAN-300W.t7 -input ../$INPUT/ -detectFaces true -mode generate -output ../$INPUT/ -device gpu -outputFormat txt
ls: '*.txt''e erişilemedi: No such file or directory
/home/levent/usr/local/torch/install/bin/luajit: ...ent/usr/local/torch/install/share/lua/5.1/trepl/init.lua:389: module 'cunn' not found:No LuaRocks module found for cunn
	no field package.preload['cunn']
	no file '/home/levent/.luarocks/share/lua/5.1/cunn.lua'
	no file '/home/levent/.luarocks/share/lua/5.1/cunn/init.lua'
	no file '/home/levent/usr/local/torch/install/share/lua/5.1/cunn.lua'
	no file '/home/levent/usr/local/torch/install/share/lua/5.1/cunn/init.lua'
	no file './cunn.lua'
	no file '/home/levent/usr/local/torch/install/share/luajit-2.1.0-beta1/cunn.lua'
	no file '/usr/local/share/lua/5.1/cunn.lua'
	no file '/usr/local/share/lua/5.1/cunn/init.lua'
	no file '/home/levent/.luarocks/lib/lua/5.1/cunn.so'
	no file '/home/levent/usr/local/torch/install/lib/lua/5.1/cunn.so'
	no file '/home/levent/usr/local/torch/install/lib/cunn.so'
	no file './cunn.so'
	no file '/usr/local/lib/lua/5.1/cunn.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'error'
	...ent/usr/local/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	process.lua:16: in main chunk
	[C]: in function 'dofile'
	...ocal/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405510
ls: '*.raw''e erişilemedi: No such file or directory

**Comment by AaronJackson** [comment]
```
luarocks install cunn
```

**Comment by levbay** [comment]
We did it but still there is an error:

Configuring incomplete, errors occurred!
See also "/tmp/luarocks_cutorch-scm-1-4745/cutorch/build/CMakeFiles/CMakeOutput.log".

Error: Failed installing dependency: https://raw.githubusercontent.com/torch/rocks/master/cutorch-scm-1.rockspec - Build error: Failed building.

**Comment by AaronJackson** [comment]
Which version of CUDA and CuDNN did you install under Fedora? 
Our readme says "CUDA (7.5 or 8.0) and CuDNN (5.1)."
