### ISSUE TITLE
how can i generate human hair on the generated 3d image

### ISSUE THREAD

**Issue by vivek12345678910** [AaronJackson/vrn#81]
When I am running the code, I am unable to see the hair over the face, Is there a way in which we can have human hair on the top of the face, I mean is this model predict only the face or Can we generate 3d part of face like hair ear etc also,

In some images, I am seeing some black part on the top and, I hope it comes because of hair color. Can we extend it to little bit such that it looks like hair of a male person.

Thanks for listening my question.

**Comment by AaronJackson** [comment]
You would need to retrain the network with data which contains hair. Not a simple task.
