### ISSUE TITLE
The obj file is rendered, but the inside is empty, so how do you fill the inside with data?

### ISSUE THREAD

**Issue by zhoujianwen** [AaronJackson/vrn#82]
Hi,Aaron
I'm a college student from China, and now we have a problem, which is how to fill the data inside the shape.The obj file is rendered, but the inside is empty, so how do you fill the inside with data?
zhoujianwenai@foxmail.com
![image](https://user-images.githubusercontent.com/13137730/40869836-91325236-6654-11e8-9685-9f3aed7d7c03.png)

**Comment by AaronJackson** [comment]
The network produces a filled face stored as an array of binary numbers. These are the raw files that are produced by the network. What you are looking at is the output from the raw2obj script, which calculates the isosurface of the volumetric representation. So, if you want a filled face,  you should load the raw file into memory and reshape it to 192x192x200 (or something like that).

**Comment by zhoujianwen** [comment]
How do you load raw files into memory? I'm trying to use PhotoShop to open raw files like this.
![image](https://user-images.githubusercontent.com/13137730/40917633-85c2512e-6836-11e8-89a8-fcd4018db70e.png)
![image](https://user-images.githubusercontent.com/13137730/40917806-105aadd6-6837-11e8-8db3-19f055572269.png)

Notepad displays as follows.
![image](https://user-images.githubusercontent.com/13137730/40917851-37b20e7e-6837-11e8-9c88-68803cb65f20.png)
All is zero......

**Comment by AaronJackson** [comment]
As per usual, raw does not have any strict definition. See the `raw2obj.py` code in this repository to show you how to open it in Python. You can probably visualise it with some software such as LiveVolume or QVox, as long as you provide the correct shape and format.

I will not be providing any further support with this issue as it does not really relate to a problem with the code.
