### ISSUE TITLE
Installing from dockerfile,but Did not respond after configuring.

### ISSUE THREAD

**Issue by realzhangliu** [AaronJackson/vrn#83]
installing from dockerfile

Configuring tzdata
------------------

Please select the geographic area in which you live. Subsequent configuration
questions will narrow this down by presenting a list of cities, representing
the time zones in which they are located.

  1. Africa      4. Australia  7. Atlantic  10. Pacific  13. Etc
  2. America     5. Arctic     8. Europe    11. SystemV
  3. Antarctica  6. Asia       9. Indian    12. US
Geographic area: 6

after a long wait,nothing happened

**Comment by AaronJackson** [comment]
I do not use Docker, it was added as a pull request from someone. If you fix the Dockerfile, I'll happily accept a pull request from you.
