### ISSUE TITLE
Logo Contribution

### ISSUE THREAD

**Issue by xzoltarianx** [AaronJackson/vrn#85]
Hello,
I am a graphic designer. I like to contribute by designing a logo for your open source software. Do you want me to design a logo for VRN?

**Comment by AaronJackson** [comment]
Hi @xzoltarianx, that's very kind of you but I am not sure what I would do with a logo

**Comment by xzoltarianx** [comment]
Logo brings works some identity and makes them more memorable. Is the project name VRN?

**Comment by AaronJackson** [comment]
Well, sure, sounds okay to me. :) 
VRN is the Volumetric Regression Network, it performs 3D face reconstruction from a single image. There is an online demo here: http://cvl-demos.cs.nott.ac.uk/vrn/
