### ISSUE TITLE
About training time....

### ISSUE THREAD

**Issue by likewind1993** [AaronJackson/vrn#93]
Thanks for your work!
I wanna know about devices and time in detail when you trained the vrn network, For example, you used TITAN GPU and spent one or two weeks train it.
These data not shown in the paper, so could you please share it?
Thank you again~

**Comment by AaronJackson** [comment]
Hey,

Two titan 1080 Ti, takes a few days assuming your CPU can keep up with
the volumetric augmentation.

Aaron


likewind1993 writes:

> Thanks for your work!
> I wanna know about devices and time in detail when you trained the vrn network, For example, you used TITAN GPU and spent one or two weeks
> train it.
> These data not shown in the paper, so could you please share it?
> Thank you again~
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.


-- 
Aaron Jackson
PhD Student, Computer Vision Laboratory, Uni of Nottingham
http://aaronsplace.co.uk

**Comment by zhoujianwen** [comment]
@likewind1993 Thank you very much for your work. I would like to know how to train volume regression network model. Is there any relevant introductory learning materials?

**Comment by zhoujianwen** [comment]
@AaronJackson  Thank you very much for your work. I would like to know how to train volume regression network model. Is there any relevant introductory learning materials?

**Comment by likewind1993** [comment]
@AaronJackson I see, thanks for your reply!

**Comment by likewind1993** [comment]
@zhoujianwen I still looking for a way to training it.

**Comment by AaronJackson** [comment]
Voxelise your dataset and train an hourglass network as described in the paper

**Comment by likewind1993** [comment]
@AaronJackson Did you meet the problem of "out of memory", I can't complete calc loss once, it shut down with error of out of memory. The calculated amount is very big(192x192x200=7372800). My computer's memory is 32GB, I don't how to optim the loss function or others, could you give me some advise?
