### ISSUE TITLE
Different results from online demo

### ISSUE THREAD

**Issue by leeeeeeo** [AaronJackson/vrn#94]
@AaronJackson Hello, thanks for your work on this project!
I ran the run.sh, and got result like this : 
![image](https://user-images.githubusercontent.com/25877709/43031817-21bdf65e-8cdc-11e8-961d-9b5e4aae6949.png)
As you can see, there are many black lines and shadows. 
But result from online demo is more smooth like this : 
![image](https://user-images.githubusercontent.com/25877709/43031842-aa97bd48-8cdc-11e8-9d1f-fd21ca8677cf.png)
 
Why is that?
Thank your very much !
I'm looking forward to your reply!

**Comment by AaronJackson** [comment]
Probably a problem with your OpenGL setup which only seems to cause a problem in the Python version and not the online one.

**Comment by leeeeeeo** [comment]
@AaronJackson I'm using python 2.7 .  
You think python 2.7 may cause the problem?
And how to set OPENGL setup ?
Thank you !

**Comment by marvelikov** [comment]
did you solve it @leeeeeeo ?
i have the exact same issue. Tried on both Windows 10 and Linux Mint 19 (Ubuntu 18.04) with gpu gtx1070, opengl 4.6

**Comment by leeeeeeo** [comment]
@marvelikov I tried project the 3D model on 2D image, and found nothing strange. I don't know what caused it, but it doesn't affect use of the 3D model.

**Comment by marvelikov** [comment]
Thanks!
