### ISSUE TITLE
Error when using matlab

### ISSUE THREAD

**Issue by leeeeeeo** [AaronJackson/vrn#95]
@AaronJackson Hello, thank you for your contribution on this work !
When I run the run.m.
An error occurred: 
![image](https://user-images.githubusercontent.com/25877709/43032787-8c9f255a-8cf1-11e8-96bb-1c79a92d43f8.png)
Could you please tell me how to solve this problem?
Thank you very much !

**Comment by AaronJackson** [comment]
What version of MATLAB are you using?

**Comment by leeeeeeo** [comment]
@AaronJackson MATLAB R2016B.
Anyway, I ran out results using txt and scaled images from run.sh...
Thank you !
