### ISSUE TITLE
How to reduce the number of facets?

### ISSUE THREAD

**Issue by gy321** [AaronJackson/vrn#97]
An OBJ file was generated after running your code, it is amazing!! But when I used 3dMAX software to open this OBJ file, I found that there were too many  facets(more than 220,000) in the model generated. Although the number of facets can be reduced using 3dMAX , is there any parameter in your code that controls the number of facets in the OBJ model generated? Or how can I modify the code to reach this goal？ Thank U！

**Comment by AaronJackson** [comment]
If you are using the matlab version you can use reducepatch. There is probably something similar in Python, but I don't know.
